# Dockerfile source - https://github.com/f0rmiga/bazel-docker-image.
image: thulioassis/bazel-docker-image:1.0.1

stages:
- lint
- build
- test
- publish

.common_refs: &common_refs
- external_pull_requests
- /^test\//
- master

lint:
  stage: lint
  only: *common_refs
  script:
  - ./dev/linters/shellcheck.sh

build:chart:
  stage: build
  only: *common_refs
  script:
  - .gitlab/pipelines/stages/build/build.sh
  artifacts:
    paths:
    - output/kubecf-*.tgz
    expire_in: 1 week

smoke-tests:
  stage: test
  only: *common_refs
  script:
  - .gitlab/pipelines/stages/deploy/setup_k8s.sh
  - .gitlab/pipelines/stages/deploy/deploy_cf_operator.sh
  - .gitlab/pipelines/stages/deploy/wait_cf_operator.sh
  - .gitlab/pipelines/stages/deploy/deploy_kubecf.sh
  - .gitlab/pipelines/stages/deploy/wait_kubecf.sh
  - .gitlab/pipelines/stages/tests/smoke_tests.sh
  - .gitlab/pipelines/stages/deploy/stop_k8s.sh

publish:chart:
  stage: publish
  only:
  - master
  image:
    name: minio/mc
    entrypoint: [""]
  script:
  - .gitlab/pipelines/stages/publish.sh
