# Dockerfile source - https://github.com/f0rmiga/bazel-docker-image.
image: thulioassis/bazel-docker-image:0.29.1

stages:
- lint
- build
- test
- publish

lint:
  stage: lint
  only:
  - external_pull_requests
  - master
  script:
  - ./dev/linters/shellcheck.sh

build:chart:
  stage: build
  only:
  - external_pull_requests
  - master
  script:
  - .gitlab/pipelines/stages/build/build.sh
  artifacts:
    paths:
    - output/kubecf-*.tgz
    expire_in: 1 week

smoke-tests:
  stage: test
  only:
  - external_pull_requests
  - master
  script:
  - .gitlab/pipelines/stages/deploy/setup.sh
  - .gitlab/pipelines/stages/deploy/deploy_cf_operator.sh
  - .gitlab/pipelines/stages/deploy/wait_cf_operator.sh
  - .gitlab/pipelines/stages/deploy/deploy_kubecf.sh
  - .gitlab/pipelines/stages/deploy/wait_kubecf.sh
  - .gitlab/pipelines/stages/tests/smoke_tests.sh

publish:chart:
  stage: publish
  only:
  - master
  image:
    name: minio/mc
    entrypoint: [""]
  script:
  - .gitlab/pipelines/stages/publish.sh
