# Dockerfile source - https://github.com/f0rmiga/bazel-docker-image.
image: thulioassis/bazel-docker-image:2.0.0

stages:
- lint
- build
- test
- publish

.common_refs: &common_refs
- external_pull_requests
- /^test\//
- master

lint:
  stage: lint
  only: *common_refs
  script:
  - ./dev/linters/shellcheck.sh
  - ./dev/linters/yamllint.sh
  - ./dev/linters/helmlint.sh

build:chart:
  stage: build
  only: *common_refs
  script:
  - .gitlab/pipelines/stages/build/build.sh
  artifacts:
    paths:
    - output/version.txt
    - output/kubecf.tgz
    - output/kubecf-bundle.tgz
    expire_in: 1 week

tests:
  stage: test
  only: *common_refs
  script:
  - /usr/bin/date
  - .gitlab/pipelines/stages/deploy/setup_k8s.sh
  - /usr/bin/date
  - .gitlab/pipelines/stages/deploy/load_images.sh
  - /usr/bin/date
  - .gitlab/pipelines/stages/deploy/deploy_cf_operator.sh
  - /usr/bin/date
  - .gitlab/pipelines/stages/deploy/wait_cf_operator.sh
  - /usr/bin/date
  - .gitlab/pipelines/stages/deploy/deploy_kubecf.sh
  - /usr/bin/date
  - .gitlab/pipelines/stages/deploy/wait_kubecf.sh
  - /usr/bin/date
  - .gitlab/pipelines/stages/tests/smoke_tests.sh
  - /usr/bin/date
  - .gitlab/pipelines/stages/tests/cf_acceptance_tests.sh
  - /usr/bin/date
  - .gitlab/pipelines/stages/deploy/stop_k8s.sh
  - /usr/bin/date

publish:chart:
  stage: publish
  only:
  - master
  image:
    name: minio/mc
    entrypoint: [""]
  script:
  - .gitlab/pipelines/stages/publish.sh
