{{- include "_config.load" $ }}
{{- /*
  Template "kubecf.implicit-var" generates the kube secret declaration for a
  variable.  It takes a list of three arguments: the context, the variable
  name, and the variable path (e.g. foo.bar.baz).
*/ -}}
{{- define "kubecf.implicit-var" }}
{{- $variable_name := (index . 1) }}
{{- $variable_path := (index . 2) }}
{{- with (first .) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "var-%s" ($variable_name | replace "_" "-" | replace "." "-") }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/name: {{ include "kubecf.fullname" . }}
    app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
    helm.sh/chart: {{ include "kubecf.chart" . }}
type: Opaque
stringData:
  value: {{ template "kubecf.dig" (list .Values ( splitList "." $variable_path )) }}
{{- end }}
{{- end }}

{{ include "kubecf.implicit-var" (list . "system_domain" "system_domain") }}

{{- range $name, $value := .Values.variables }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "var-%s" ($name | replace "_" "-" | replace "." "-") | quote }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ $.Release.Service | quote }}
    app.kubernetes.io/name: {{ include "kubecf.fullname" $ }}
    app.kubernetes.io/version: {{ default $.Chart.Version $.Chart.AppVersion | quote }}
    helm.sh/chart: {{ include "kubecf.chart" $ }}
type: Opaque
stringData:
  value: {{ $value | quote }}
{{- end }}
