system_domain: ~

# Set or override job properties. The first level of the map is the instance group name. The second
# level of the map is the job name. E.g.:
#  properties:
#    adapter:
#      adapter:
#        scalablesyslog:
#          adapter:
#            logs:
#              addr: kubecf-log-api:8082
#
#  Eirini Persistence Broker setup example:
#
# properties:
#   eirini:
#     eirini-persi-broker:
#       eirini-persi-broker:
#         service_plans:
#           - id: "default"
#             name: "default"
#             description: "Persistence storage service broker for applications."
#             free: true
#             kube_storage_class: "default"
#             default_size: "1Gi"
properties: {}

kube:
  # The storage class to be used for the instance groups that need it (e.g. bits, database and
  # singleton-blobstore). If it's not set, the default storage class will be used.
  storage_class: ~
  # The service_cluster_ip_range and pod_cluster_ip_range are used by the internal security group
  # definition to allow apps to communicate with internal service brokers (e.g. credhub).
  # service_cluster_ip_range can be fetched with the following command, assuming that the API
  # server started with the `--service-cluster-ip-range` flag:
  # kubectl cluster-info dump --output yaml \
  #   | awk 'match($0, /service-cluster-ip-range=(.*)/, range) { print range[1] }'
  # The default value for `--service-cluster-ip-range` is 10.0.0.0/24.
  service_cluster_ip_range: ~
  # pod_cluster_ip_range can be fetched with the following command, assuming that the controller
  # manager started with the `--cluster-cidr` flag:
  # kubectl cluster-info dump --output yaml \
  #   | awk 'match($0, /cluster-cidr=(.*)/, range) { print range[1] }'
  # There is no default value for `--cluster-cidr`.
  pod_cluster_ip_range: ~

releases:
  # The defaults for all releases, where we do not otherwise override them.
  defaults:
    url: docker.io/cfcontainerization
    stemcell:
      os: SLE_15_SP1
      version: 15.1-7.0.0_374.gb8e8e6af
  app-autoscaler:
    version: 3.0.0
    stemcell:
      os: opensuse-42.3
      version: 36.g03b4653-30.80-7.0.0_367.g6b06e343
  bits-service:
    stemcell:
      os: opensuse-42.3
      version: 36.g03b4653-30.80-7.0.0_348.gc8fb3864
  brain-tests:
    stemcell:
      os: opensuse-42.3
      version: 36.g03b4653-30.80-7.0.0_372.ge3509601
  cf-acceptance-tests:
    version: 0.0.9
    stemcell:
      os: SLE_15_SP1
      version: 21.3-7.0.0_374.gb8e8e6af
  cf-mysql:
    version: 36.19.0
    stemcell:
      os: opensuse-42.3
      version: 36.g03b4653-30.80-7.0.0_360.g0ec8d681
  postgres:
    version: "39"
    stemcell:
      os: opensuse-42.3
      version: 36.g03b4653-30.80-7.0.0_367.g6b06e343
  sle15:
    url: registry.suse.com/cap-staging
    version: "10.70"
    stemcell:
      os: SLE-12SP4
      version: 11.g2837aef-0.233-7.0.0_372.ge3509601

multi_az: false
high_availability: false

# Sizing takes precedence over the high_availability property. I.e. setting the instance count
# for an instance group greater than 1 will make it highly available.
sizing:
  adapter:
    instances: ~
  api:
    instances: ~
  asactors:
    instances: ~
  asapi:
    instances: ~
  asmetrics:
    instances: ~
  asnozzle:
    instances: ~
  auctioneer:
    instances: ~
  bits:
    instances: ~
  cc_worker:
    instances: ~
  credhub:
    instances: ~
  diego_api:
    instances: ~
  diego_cell:
    instances: ~
  doppler:
    instances: ~
  eirini:
    instances: ~
  log_api:
    instances: ~
  nats:
    instances: ~
  router:
    instances: ~
  routing_api:
    instances: ~
  scheduler:
    instances: ~
  uaa:
    instances: ~
  tcp_router:
    instances: ~

# Service is only valid to set a external endpoints for the instance groups if
# features.ingress.enabled is false.
services:
  router:
    annotations: ~
    type: LoadBalancer
    externalIPs: []
    clusterIP: ~
  ssh-proxy:
    annotations: ~
    type: LoadBalancer
    externalIPs: []
    clusterIP: ~
  tcp-router:
    annotations: ~
    type: LoadBalancer
    externalIPs: []
    clusterIP: ~
    port_range:
      start: 20000
      end: 20008

features:
  eirini:
    enabled: false
    registry:
      service:
        nodePort: 32123
  ingress:
    enabled: false
    tls:
      crt: ~
      key: ~
    annotations: {}
    labels: {}
  # TODO: suse_buildpacks should be default to true after the opensuse-stemcell-based images are
  # published to docker.io.
  suse_buildpacks: false
  autoscaler:
    enabled: false
  sle15_stack:
    enabled: true

  # external_database disables the embedded database and allows using an external, already seeded,
  # database.
  # The database type can be either 'mysql' or 'postgres'.
  external_database:
    enabled: false
    type: ~
    host: ~
    port: ~
    databases:
      uaa:
        name: uaa
        password: ~
        username: ~
      cc:
        name: cloud_controller
        password: ~
        username: ~
      bbs:
        name: diego
        password: ~
        username: ~
      routing_api:
        name: routing-api
        password: ~
        username: ~
      policy_server:
        name: network_policy
        password: ~
        username: ~
      silk_controller:
        name: network_connectivity
        password: ~
        username: ~
      locket:
        name: locket
        password: ~
        username: ~
      credhub:
        name: credhub
        password: ~
        username: ~

# Enable or disable instance groups for the different test suites.
# Only smoke tests should be run in production environments.
testing:
  brain_tests:
    enabled: false
  cf_acceptance_tests:
    enabled: false
  smoke_tests:
    enabled: true

operations:
  # A list of configmap names that should be applied to the BOSH manifest.
  custom: []

k8s-host-url: ""
k8s-service-token: ""
k8s-service-username: ""
k8s-node-ca: ""
