# SITS only makes sense when using Diego, for this reason, we only enable it if Eirini is not
# enabled.
{{- if and .Values.testing.sync_integration_tests.enabled (not .Values.features.eirini.enabled) }}

- path: /instance_groups/-
  type: replace
  value:
    azs:
    - z1
    env:
      bosh:
        agent:
          settings:
            serviceAccountName: tests-sits
            disable_log_sidecar: true
            jobBackoffLimit: 1
    instances: 1
    jobs:
    - name: sync-integration-tests
      properties:
        quarks:
          bpm:
            processes: []
        sync_integration_tests:
          bbs:
            svc:
              name: diego-api
              namespace: {{ .Release.Namespace }}
              port: 8889
          config:
            bbs_client_cert_contents: ((diego_bbs_client.certificate))
            bbs_client_key_contents: ((diego_bbs_client.private_key))
            cf_admin_user: admin
            cf_admin_password: ((cf_admin_password))
            cf_api: api.((system_domain))
            cf_apps_domain: ((system_domain))
            cf_skip_ssl_validation: true
          setup:
            flake_attempts: 3
            nodes: 4
            verbose: false
      release: sync-integration-tests
    lifecycle: errand
    name: sync-integration-tests
    networks:
    - name: default
    stemcell: default
    update:
      serial: true
    vm_type: minimal

{{- if .Values.testing.sync_integration_tests.delete_pod }}
- type: replace
  path: /instance_groups/name=sync-integration-tests/env?/bosh/agent/settings/labels/delete
  value: "pod"
{{- end }}

{{- end }}
