features:
  eirini:
    # Currently the stack rootfs for Eirini is pre-installed in the
    # bits-service image, so the eirini feature can only be enabled
    # when "install_stacks" is set to a list that only includes the
    # stack specified by "features.eirini.stack".
    stack: sle15

eirini:
  opi:
    deny_app_ingress: false
    image_tag: "1.8.0.1"
    image: registry.suse.com/cap-staging/opi
    metrics_collector_image: registry.suse.com/cap-staging/metrics-collector
    bits_waiter_image: registry.suse.com/cap-staging/bits-waiter
    route_collector_image: registry.suse.com/cap-staging/route-collector
    route_pod_informer_image: registry.suse.com/cap-staging/route-pod-informer
    route_statefulset_informer_image: registry.suse.com/cap-staging/route-statefulset-informer
    event_reporter_image: registry.suse.com/cap-staging/event-reporter
    event_reporter_image_tag: "1.8.0"
    staging_reporter_image: registry.suse.com/cap-staging/staging-reporter
    staging_reporter_image_tag: "1.8.0"
    registry_secret_name: eirini-registry-credentials
    disk_limit_mb: 2048
    namespace: eirini
    version: 0.0.0

    cc_api:
      # The service that the CC API listens on; may be a FQDN instead.
      serviceName: "api"

    # The TLS secrets are generated by quarks-operator and should be HIDDEN from the user.
    tls:
      opiCapiClient:
        secretName: {{ include "kubecf.varSecretName" (list $ "eirini_tls_client_cert") }}
        keyPath: "private_key"
        certPath: "certificate"
      opiServer:
        secretName: {{ include "kubecf.varSecretName" (list $ "eirini_tls_server_cert") }}
        certPath: "certificate"
        keyPath: "private_key"
      capi:
        secretName: {{ include "kubecf.varSecretName" (list $ "eirini_tls_server_cert") }}
        caPath: "ca"
      eirini:
        secretName: {{ include "kubecf.varSecretName" (list $ "eirini_tls_server_cert") }}
        caPath: "ca"

    # components
    events:
      # Events should always be enabled and HIDDEN from the user.
      enable: true
      # All configs in this section should be HIDDEN from the user; they are
      # here to adapt the Eirini helm chart for KubeCF use.
      tls:
        capiClient:
          secretName: {{ include "kubecf.varSecretName" (list $ "cc_tls") }}
          keyPath: "private_key"
          certPath: "certificate"
        capi:
          secretName: {{ include "kubecf.varSecretName" (list $ "cc_tls") }}
          caPath: "ca"

    logs:
      # changing this breaks logging.
      serviceName: doppler

    # All configs in this section should be HIDDEN from the user; they are here
    # to adapt the Eirini helm chart for KubeCF use.
    metrics:
      enable: true
      tls:
        client:
          secretName: {{ include "kubecf.varSecretName" (list $ "loggregator_tls_doppler") }}
          keyPath: "private_key"
          certPath: "certificate"
        server:
          secretName: {{ include "kubecf.varSecretName" (list $ "loggregator_tls_doppler") }}
          caPath: "ca"

    # All configs in this section should be HIDDEN from the user; they are here
    # to adapt the Eirini helm chart for KubeCF use.
    routing:
      enable: true
      nats:
        secretName: {{ include "kubecf.varSecretName" (list $ "nats_password") }}
        passwordPath: "password"
        serviceName: "nats"

    staging:
      enable: true
      application_service_account: "eirini"
      staging_service_account: "eirini"
      downloader_image: registry.suse.com/cap-staging/recipe-downloader
      downloader_image_tag: "1.8.0-24.56"
      executor_image: registry.suse.com/cap-staging/recipe-executor
      executor_image_tag: "1.8.0-24.56"
      uploader_image: registry.suse.com/cap-staging/recipe-uploader
      uploader_image_tag: "1.8.0-24.56"
      # The TLS secrets are generated by quarks-operator and should be HIDDEN from the user.
      tls:
        client:
          secretName: {{ include "kubecf.varSecretName" (list $ "eirini_tls_client_cert") }}
          certPath: "certificate"
          keyPath: "private_key"
        cc_uploader:
          secretName: {{ include "kubecf.varSecretName" (list $ "cc_bridge_cc_uploader") }}
          certPath: "certificate"
          keyPath: "private_key"
        ca:
          secretName: {{ include "kubecf.varSecretName" (list $ "eirini_tls_client_cert") }}
          path: "ca"
        stagingReporter:
          secretName: {{ include "kubecf.varSecretName" (list $ "eirini_tls_client_cert") }}
          certPath: "certificate"
          keyPath: "private_key"
          caPath: "ca"
