# Disable BOSH DNS and set the logs addr manually.
- type: replace
  path: /instance_groups/name=adapter/jobs/name=adapter/properties/scalablesyslog/adapter/bosh_dns?
  value: false
- type: replace
  path: /instance_groups/name=adapter/jobs/name=adapter/properties/scalablesyslog/adapter/logs?/addr
  value: ((deployment-name))-log-api:8082

# Add quarks properties.
- type: replace
  path: /instance_groups/name=adapter/jobs/name=adapter/properties/quarks?
  value:
    ports:
    - name: adapter
      protocol: TCP
      internal: 4443
