# Disable BOSH DNS and set the logs addr manually.
- type: replace
  path: /instance_groups/name=adapter/jobs/name=adapter/properties/scalablesyslog/adapter/bosh_dns?
  value: false
- type: replace
  path: /instance_groups/name=adapter/jobs/name=adapter/properties/scalablesyslog/adapter/logs?/addr
  value: ((deployment-name))-log-api:8082

# Add bosh_containerization properties.
- type: replace
  path: /instance_groups/name=adapter/jobs/name=adapter/properties/bosh_containerization?
  value:
    ports:
    - name: adapter
      protocol: TCP
      internal: 4443
    run:
      healthcheck:
        adapter:
          readiness:
            exec:
              command: ['curl', '--fail', '--head', 'http://127.0.0.1:8080/health']
