# TODO: Remove this replace once all buildpacks are included.
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/install_buildpacks
  value:
  - name: binary_buildpack
    package: binary-buildpack-cflinuxfs3

# TODO: Remove these `remove` once all buildpack images are built.
- type: remove
  path: /instance_groups/name=api/jobs/name=dotnet-core-buildpack
- type: remove
  path: /instance_groups/name=api/jobs/name=go-buildpack
- type: remove
  path: /instance_groups/name=api/jobs/name=java-buildpack
- type: remove
  path: /instance_groups/name=api/jobs/name=nodejs-buildpack
- type: remove
  path: /instance_groups/name=api/jobs/name=nginx-buildpack
- type: remove
  path: /instance_groups/name=api/jobs/name=r-buildpack
- type: remove
  path: /instance_groups/name=api/jobs/name=php-buildpack
- type: remove
  path: /instance_groups/name=api/jobs/name=python-buildpack
- type: remove
  path: /instance_groups/name=api/jobs/name=ruby-buildpack
- type: remove
  path: /instance_groups/name=api/jobs/name=staticfile-buildpack

# Set the common name for the cc_bridge_cc_uploader_server certificate.
- type: replace
  path: /variables/name=cc_bridge_cc_uploader_server/options/common_name?
  value: ((deployment-name))-api

- type: replace
  path: /variables/name=cc_bridge_cc_uploader_server/options/alternative_names?
  value:
  - ((deployment-name))-api

- type: replace
  path: /variables/name=cc_logcache_tls/options/alternative_names?
  value:
  - ((deployment-name))-api

- type: replace
  path: /variables/name=cc_tls/options/common_name?
  value: ((deployment-name))-api

# core_file_pattern should be disabled as CC is not running on a VM.
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/core_file_pattern?
  value: false

# Disable tuning /proc/sys kernel parameters as file_server is running on a container.
- type: replace
  path: /instance_groups/name=api/jobs/name=file_server/properties/set_kernel_parameters?
  value: false

# We don't have a /var/vcap/job/*/packages directory, so we point to all the packages
- type: replace
  path: /instance_groups/name=api/jobs/name=file_server/properties/diego?/file_server?/static_directory?
  value: "/var/vcap/packages/"

# TODO: Figure out the DB encryption validation.
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/database_encryption?/skip_validation?
  value: true

# Don't run migrations in pre-start, it seems flaky
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/run_prestart_migrations?
  value: false

# Set the common name for the cc_bridge_cc_uploader_server certificate.
- type: replace
  path: /variables/name=cc_bridge_cc_uploader_server/options/common_name
  value: ((deployment-name))-api
- type: replace
  path: /variables/name=cc_bridge_cc_uploader_server/options/alternative_names
  value:
  - ((deployment-name))-api

# Set the common name for the network_policy_server certificate.
- type: replace
  path: /variables/name=network_policy_server/options/common_name
  value: ((deployment-name))-api
- type: replace
  path: /variables/name=network_policy_server/options/alternative_names?
  value:
  - ((deployment-name))-api

# Override the addresses for the jobs under the api instance group.
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/ccdb/address
  value: ((deployment-name))-database
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/buildpacks?/webdav_config/private_endpoint
  value: &blobstore_url https://((deployment-name))-singleton-blobstore:4443
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/droplets?/webdav_config/private_endpoint
  value: *blobstore_url
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/packages?/webdav_config/private_endpoint
  value: *blobstore_url
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/resource_pool?/webdav_config/private_endpoint
  value: *blobstore_url
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/diego?/bbs/url
  value: https://((deployment-name))-diego-api:8889
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/diego?/file_server_url
  value: http://((deployment-name))-api:8080
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/diego?/cc_uploader_https_url
  value: https://((deployment-name))-api:9091
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/internal_service_hostname?
  value: ((deployment-name))-api
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/logcache?/host
  value: ((deployment-name))-doppler
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/loggregator?/internal_url
  value: http://((deployment-name))-log-api:8081
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/credhub_api?/hostname
  value: ((deployment-name))-credhub
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/uaa?/internal_url
  value: ((deployment-name))-uaa
- type: replace
  path: /instance_groups/name=api/jobs/name=routing-api/properties/routing_api/sqldb/host
  value: ((deployment-name))-database
- type: replace
  path: /instance_groups/name=api/jobs/name=routing-api/properties/routing_api/locket/api_location
  value: ((deployment-name))-diego-api:8891
- type: replace
  path: /instance_groups/name=api/jobs/name=routing-api/properties/dns_health_check_host?
  value: ((deployment-name))-uaa
- type: replace
  path: /instance_groups/name=api/jobs/name=routing-api/properties/uaa/token_endpoint?
  value: ((deployment-name))-uaa
- type: replace
  path: /instance_groups/name=api/jobs/name=route_registrar/properties/nats?/machines
  value:
  - ((deployment-name))-nats
- type: replace
  path: /instance_groups/name=api/jobs/name=route_registrar/properties/route_registrar?/routing_api/api_url
  value: http://((deployment-name))-api:3000
- type: replace
  path: /instance_groups/name=api/jobs/name=route_registrar/properties/route_registrar?/routing_api/oauth_url
  value: https://((deployment-name))-uaa:8443
- type: replace
  path: /instance_groups/name=api/jobs/name=policy-server/properties/database/host
  value: ((deployment-name))-database
- type: replace
  path: /instance_groups/name=api/jobs/name=policy-server/properties/uaa_hostname?
  value: ((deployment-name))-uaa

# Add empty BPM processes to buildpacks.
- type: replace
  path: /instance_groups/name=api/jobs/name=binary-buildpack/properties?/quarks?/bpm?/processes?
  value: []

# Add quarks properties for cloud_controller_ng.
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/quarks?
  value:
    ports:
    - name: api
      protocol: TCP
      internal: 9022
    - name: api-tls
      protocol: TCP
      internal: 9023
    - name: api-mutual-tls
      protocol: TCP
      internal: 9024

# Add quarks properties for routing-api.
- type: replace
  path: /instance_groups/name=api/jobs/name=routing-api/properties/quarks?
  value:
    ports:
    - name: routing-api
      protocol: TCP
      internal: 3000

# Add quarks properties for cc_uploader.
- type: replace
  path: /instance_groups/name=api/jobs/name=cc_uploader/properties/quarks?
  value:
    ports:
    - name: cc-uploader
      protocol: TCP
      internal: 9090

# Add quarks properties for file_server.
- type: replace
  path: /instance_groups/name=api/jobs/name=file_server/properties/quarks?
  value:
    ports:
    - name: file-server
      protocol: TCP
      internal: &file-server-port 8080
    run:
      healthcheck:
        file_server:
          readiness:
            tcpSocket:
              port: *file-server-port

# Add quarks properties for statsd_injector.
- type: replace
  path: /instance_groups/name=api/jobs/name=statsd_injector/properties/quarks?
  value:
    ports:
    # TODO: Can we remove this port?
    - name: statsd
      protocol: TCP
      internal: 8125

# Add quarks properties for policy-server.
- type: replace
  path: /instance_groups/name=api/jobs/name=policy-server/properties/quarks?
  value:
    ports:
    - name: policy-server
      protocol: TCP
      internal: 4002
