- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/install_buildpacks
  value:
  ## Order is important here
  - name: staticfile_buildpack
    file: /var/vcap/data/shared-packages/staticfile-buildpack/packages/staticfile-buildpack-cflinuxfs3/staticfile_buildpack-cflinuxfs3-v1.4.40.zip
  - name: java_buildpack
    file: /var/vcap/data/shared-packages/java-buildpack/packages/java-buildpack-cflinuxfs3/java-buildpack-cflinuxfs3-v4.18.zip
  - name: ruby_buildpack
    file: /var/vcap/data/shared-packages/ruby-buildpack/packages/ruby-buildpack-cflinuxfs3/ruby_buildpack-cflinuxfs3-v1.7.36.zip
  - name: dotnet_core_buildpack
    file: /var/vcap/data/shared-packages/dotnet-core-buildpack/packages/dotnet-core-buildpack-cflinuxfs3/dotnet-core_buildpack-cflinuxfs3-v2.2.7.zip
  - name: nodejs_buildpack
    file: /var/vcap/data/shared-packages/nodejs-buildpack/packages/nodejs-buildpack-cflinuxfs3/nodejs_buildpack-cflinuxfs3-v1.6.45.zip
  - name: go_buildpack
    file: /var/vcap/data/shared-packages/go-buildpack/packages/go-buildpack-cflinuxfs3/go_buildpack-cflinuxfs3-v1.8.35.zip
  - name: python_buildpack
    file: /var/vcap/data/shared-packages/python-buildpack/packages/python-buildpack-cflinuxfs3/python_buildpack-cflinuxfs3-v1.6.29.zip
  - name: php_buildpack
    file: /var/vcap/data/shared-packages/php-buildpack/packages/php-buildpack-cflinuxfs3/php_buildpack-cflinuxfs3-v4.3.72.zip
  - name: nginx_buildpack
    file: /var/vcap/data/shared-packages/nginx-buildpack/packages/nginx-buildpack-cflinuxfs3/nginx_buildpack-cflinuxfs3-v1.0.9.zip
  - name: r_buildpack
    file: /var/vcap/data/shared-packages/r-buildpack/packages/r-buildpack-cflinuxfs3/r_buildpack-cflinuxfs3-v1.0.7.zip
  - name: binary_buildpack
    file: /var/vcap/data/shared-packages/binary-buildpack/packages/binary-buildpack-cflinuxfs3/binary_buildpack-cflinuxfs3-v1.0.31.zip

# core_file_pattern should be disabled as CC is not running on a VM.
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/core_file_pattern?
  value: false

# Disable tuning /proc/sys kernel parameters as file_server is running on a container.
- type: replace
  path: /instance_groups/name=api/jobs/name=file_server/properties/set_kernel_parameters?
  value: false

# We don't have a /var/vcap/job/*/packages directory, so we point to all the packages.
- type: replace
  path: /instance_groups/name=api/jobs/name=file_server/properties/diego?/file_server/static_directory
  value: "/var/vcap/packages/"

# TODO: Figure out the DB encryption validation.
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/database_encryption?/skip_validation?
  value: true

# Don't run migrations in pre-start, it seems flaky.
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/run_prestart_migrations?
  value: false

# Override the addresses for the jobs under the api instance group.
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/ccdb/address
  value: {{ .Values.deployment_name }}-database
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/buildpacks?/webdav_config/private_endpoint
  value: &blobstore_url https://{{ .Values.deployment_name }}-singleton-blobstore.{{ .Release.Namespace }}:4443
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/droplets?/webdav_config/private_endpoint
  value: *blobstore_url
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/packages?/webdav_config/private_endpoint
  value: *blobstore_url
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/resource_pool?/webdav_config/private_endpoint
  value: *blobstore_url
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/diego?/bbs/url
  value: https://{{ .Values.deployment_name }}-diego-api:8889
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/diego?/file_server_url
  value: http://{{ .Values.deployment_name }}-api:8080
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/internal_service_hostname?
  value: {{ .Values.deployment_name }}-api.{{ .Release.Namespace }}
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/logcache?/host
  value: {{ .Values.deployment_name }}-doppler
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/loggregator?/internal_url
  value: https://{{ .Values.deployment_name }}-log-api:8081
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/credhub_api?/hostname
  value: {{ .Values.deployment_name }}-credhub
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/uaa?/internal_url
  value: {{ .Values.deployment_name }}-uaa
- type: replace
  path: /instance_groups/name=api/jobs/name=routing-api/properties/routing_api/sqldb/host
  value: {{ .Values.deployment_name }}-database
- type: replace
  path: /instance_groups/name=api/jobs/name=routing-api/properties/routing_api/locket/api_location
  value: {{ .Values.deployment_name }}-diego-api:8891
- type: replace
  path: /instance_groups/name=api/jobs/name=routing-api/properties/dns_health_check_host?
  value: {{ .Values.deployment_name }}-uaa
- type: replace
  path: /instance_groups/name=api/jobs/name=routing-api/properties/uaa/token_endpoint?
  value: {{ .Values.deployment_name }}-uaa
- type: replace
  path: /instance_groups/name=api/jobs/name=route_registrar/properties/nats?/machines
  value:
  - {{ .Values.deployment_name }}-nats
- type: replace
  path: /instance_groups/name=api/jobs/name=route_registrar/properties/route_registrar/routing_api?/api_url
  value: http://{{ .Values.deployment_name }}-api:3000
- type: replace
  path: /instance_groups/name=api/jobs/name=route_registrar/properties/route_registrar/routing_api?/oauth_url
  value: https://{{ .Values.deployment_name }}-uaa:8443
- type: replace
  path: /instance_groups/name=api/jobs/name=policy-server/properties/database/host
  value: {{ .Values.deployment_name }}-database
- type: replace
  path: /instance_groups/name=api/jobs/name=policy-server/properties/uaa_hostname?
  value: {{ .Values.deployment_name }}-uaa
- type: replace
  path: /instance_groups/name=api/jobs/name=cc_uploader/properties/internal_hostname?
  value: {{ .Values.deployment_name }}-api.{{ .Release.Namespace }}

# Add empty BPM processes to buildpacks.
- type: replace
  path: /instance_groups/name=api/jobs/name=binary-buildpack/properties?/quarks/bpm/processes
  value: []
- type: replace
  path: /instance_groups/name=api/jobs/name=dotnet-core-buildpack/properties?/quarks/bpm/processes
  value: []
- type: replace
  path: /instance_groups/name=api/jobs/name=go-buildpack/properties?/quarks/bpm/processes
  value: []
- type: replace
  path: /instance_groups/name=api/jobs/name=java-buildpack/properties?/quarks/bpm/processes
  value: []
- type: replace
  path: /instance_groups/name=api/jobs/name=nodejs-buildpack/properties?/quarks/bpm/processes
  value: []
- type: replace
  path: /instance_groups/name=api/jobs/name=nginx-buildpack/properties?/quarks/bpm/processes
  value: []
- type: replace
  path: /instance_groups/name=api/jobs/name=r-buildpack/properties?/quarks/bpm/processes
  value: []
- type: replace
  path: /instance_groups/name=api/jobs/name=php-buildpack/properties?/quarks/bpm/processes
  value: []
- type: replace
  path: /instance_groups/name=api/jobs/name=python-buildpack/properties?/quarks/bpm/processes
  value: []
- type: replace
  path: /instance_groups/name=api/jobs/name=ruby-buildpack/properties?/quarks/bpm/processes
  value: []
- type: replace
  path: /instance_groups/name=api/jobs/name=staticfile-buildpack/properties?/quarks/bpm/processes
  value: []

# Add quarks properties for cloud_controller_ng.
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/quarks?
  value:
    ports:
    - name: api
      protocol: TCP
      internal: 9022
    - name: api-tls
      protocol: TCP
      internal: 9023
    - name: api-mutual-tls
      protocol: TCP
      internal: 9024
    run:
      healthcheck:
        cloud_controller_ng:
          readiness: &cloud_controller_ng_readiness
            exec:
              command: [curl, --fail, --head, --silent, http://127.0.0.1:9022/healthz]
    post_start:
      condition: *cloud_controller_ng_readiness

# Add quarks properties for routing-api.
- type: replace
  path: /instance_groups/name=api/jobs/name=routing-api/properties/quarks?
  value:
    ports:
    - name: routing-api
      protocol: TCP
      internal: 3000

# Add quarks properties for cc_uploader.
- type: replace
  path: /instance_groups/name=api/jobs/name=cc_uploader/properties/quarks?
  value:
    ports:
    - name: http
      protocol: TCP
      internal: 9090
    - name: https
      protocol: TCP
      internal: 9091

# Add quarks properties for file_server.
- type: replace
  path: /instance_groups/name=api/jobs/name=file_server/properties/quarks?
  value:
    ports:
    - name: file-server
      protocol: TCP
      internal: &file-server-port 8080
    run:
      healthcheck:
        file_server:
          readiness:
            tcpSocket:
              port: *file-server-port

# Add quarks properties for statsd_injector.
- type: replace
  path: /instance_groups/name=api/jobs/name=statsd_injector/properties/quarks?
  value:
    ports:
    # TODO: Can we remove this port?
    - name: statsd
      protocol: TCP
      internal: 8125

# Add quarks properties for policy-server.
- type: replace
  path: /instance_groups/name=api/jobs/name=policy-server/properties/quarks?
  value:
    ports:
    - name: policy-server
      protocol: TCP
      internal: 4002
    run:
      healthcheck:
        policy-server:
          readiness: &policy_server_readiness
            exec:
              command:
              - sh
              - -c
              - ss -nlt | grep "LISTEN.*:4002"
    post_start:
      condition: *policy_server_readiness

# Add quarks properties for policy-server-internal.
- type: replace
  path: /instance_groups/name=api/jobs/name=policy-server-internal/properties/quarks?
  value:
    run:
      healthcheck:
        policy-server:
          readiness: &policy_server_internal_readiness
            exec:
              command:
              - sh
              - -c
              # TODO: Use curl to call port 31946.
              - ss -nlt | grep "LISTEN.*:4003"
    post_start:
      condition: *policy_server_internal_readiness

{{- $root := . -}}
{{- range $path, $bytes := .Files.Glob "assets/operations/pre_render_scripts/api_*" }}
{{ $root.Files.Get $path }}
{{- end }}
