# Selectively remove jobs temporarily.
- type: remove
  path: /instance_groups/name=scheduler/jobs/name=log-cache-expvar-forwarder

# Override the addresses for the jobs under the scheduler instance group.
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cc_deployment_updater/properties/ccdb/address?
  value: ((deployment-name))-database
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cc_deployment_updater/properties/cc/diego?/bbs/url
  value: https://((deployment-name))-diego-api:8889
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cc_deployment_updater/properties/cc/diego?/cc_uploader_url
  value: http://((deployment-name))-api:9090
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cc_deployment_updater/properties/cc/diego?/file_server_url
  value: http://((deployment-name))-api:8080
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cc_deployment_updater/properties/cc/locket?/host
  value: ((deployment-name))-diego-api
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=auctioneer/properties/diego/auctioneer/bbs?/api_location
  value: ((deployment-name))-diego-api:8889
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=auctioneer/properties/diego/auctioneer/locket?/api_location
  value: ((deployment-name))-diego-api:8891
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=tps/properties/capi/tps/bbs?/api_location
  value: ((deployment-name))-diego-api:8889
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=tps/properties/capi/tps/cc/internal_service_hostname?
  value: ((deployment-name))-api
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=tps/properties/capi/tps/watcher/locket/api_location
  value: ((deployment-name))-diego-api:8891
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/ccdb/address
  value: ((deployment-name))-database
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/cc/buildpacks?/webdav_config/private_endpoint
  value: &blobstore_url https://((deployment-name))-singleton-blobstore:4443
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/cc/droplets?/webdav_config/private_endpoint
  value: *blobstore_url
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/cc/packages?/webdav_config/private_endpoint
  value: *blobstore_url
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/cc/resource_pool?/webdav_config/private_endpoint
  value: *blobstore_url
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/cc/diego?/bbs/url
  value: https://((deployment-name))-diego-api:8889
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/cc/diego?/cc_uploader_url
  value: http://((deployment-name))-api:9090
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/cc/diego?/file_server_url
  value: http://((deployment-name))-api:8080
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/cc/internal_service_hostname?
  value: ((deployment-name))-api
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/cc/uaa?/internal_url
  value: ((deployment-name))-uaa
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/credhub_api?/hostname
  value: ((deployment-name))-credhub
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cfdot/properties/bbs?/hostname
  value: ((deployment-name))-diego-api
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cfdot/properties/locket?/hostname
  value: ((deployment-name))-diego-api
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=scheduler/properties/scalablesyslog/scheduler/api/url
  value: https://((deployment-name))-api:9023
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=scheduler/properties/scalablesyslog/scheduler/tls/api/cn
  value: ((deployment-name))-api
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=ssh_proxy/properties/diego/ssh_proxy/bbs?/api_location
  value: ((deployment-name))-diego-api:8889
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=ssh_proxy/properties/diego/ssh_proxy/uaa?/url
  value: https://((deployment-name))-uaa

# Add quarks properties for the scheduler job.
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=scheduler/properties/quarks?
  value:
    run:
      healthcheck:
        scheduler:
          readiness:
            exec:
              command: ['curl', '--fail', '--head', 'http://127.0.0.1:8080/health']

# Add quarks properties for the auctioneer job.
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=auctioneer/properties/quarks?
  value:
    ports:
    - name: auctioneer
      protocol: TCP
      internal: 9016
    run:
      healthcheck:
        auctioneer:
          readiness:
            exec:
              command: ['curl', '--fail', '--head', 'http://127.0.0.1:8080/health']

# Add quarks properties for the ssh_proxy job.
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=ssh_proxy/properties/quarks?
  value:
    ports:
    - name: ssh-proxy
      protocol: TCP
      internal: 2222

- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cfdot/properties/quarks?/bpm/processes
  value: []

- type: replace
  path: /variables/name=diego_auctioneer_server/options/common_name
  value: ((deployment-name))-scheduler
- type: replace
  path: /variables/name=diego_auctioneer_server/options/alternative_names
  value:
  # TODO: Figure out how to do wildcard for this certificate as the original alternative names
  # included "*.auctioneer.service.cf.internal".
  # - "*.((deployment-name))-scheduler"
  - ((deployment-name))-scheduler
