# Selectively remove jobs temporarily.
- type: remove
  path: /instance_groups/name=singleton-blobstore/jobs/name=route_registrar

# Set the common name for the blobstore_tls.
- type: replace
  path: /variables/name=blobstore_tls/options/common_name?
  value: ((deployment-name))-singleton-blobstore

# Configure the persistent disk in the way that cf-operator can provision.
- type: remove
  path: /instance_groups/name=singleton-blobstore/persistent_disk_type
- type: replace
  path: /instance_groups/name=singleton-blobstore/persistent_disk?
  value: 102400 # 100GB

- type: replace
  path: /instance_groups/name=singleton-blobstore/jobs/name=blobstore/properties/bosh_containerization?
  value:
    ports:
    - name: http
      protocol: TCP
      internal: 8080
    - name: https
      protocol: TCP
      internal: 4443
    run:
      memory: 512
      virtual-cpus: 2
      healthcheck:
        nginx: &healthcheck
          readiness: &probe
            exec:
              command: ['sh', '-c', 'ss -nlt | grep "LISTEN.*:8080" && ss -nlt | grep "LISTEN.*:4443"']
          liveness: *probe
        url_signer: *healthcheck
