# Override the database address.
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaadb/address?
  value: {{ .Values.deployment_name }}-database

# Override the addresses for the jobs under the uaa instance group.
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaa/zones/internal/hostnames
  value:
  - {{ .Values.deployment_name }}-uaa
- type: replace
  path: /instance_groups/name=uaa/jobs/name=route_registrar/properties/nats?/machines
  value:
  - {{ .Values.deployment_name }}-nats
- type: replace
  path: /instance_groups/name=uaa/jobs/name=route_registrar/properties/route_registrar?/routing_api/api_url
  value: http://{{ .Values.deployment_name }}-api:3000
- type: replace
  path: /instance_groups/name=uaa/jobs/name=route_registrar/properties/route_registrar?/routing_api/oauth_url
  value: https://{{ .Values.deployment_name }}-uaa:8443

# Add quarks properties.
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/quarks?
  value:
    ports:
    - name: http
      protocol: TCP
      internal: 8080
    - name: https
      protocol: TCP
      internal: 8443
    run:
      healthcheck:
        uaa:
          readiness: &uaa_readiness
            exec:
              command: ['sh', '-c', '/var/vcap/jobs/uaa/bin/health_check']
    post_start:
      condition: *uaa_readiness

{{- $root := . -}}
{{- range $path, $bytes := .Files.Glob "assets/operations/pre_render_scripts/uaa_*" }}
{{ $root.Files.Get $path }}
{{- end }}
