- type: replace
  path: /variables/name=log_cache_ca/options/common_name?
  value: log-cache-ca

# ---------------------------------------
- type: replace
  path: /variables/name=network_policy_server/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-api'
# ---------------------------------------
- type: replace
  path: /variables/name=network_policy_client/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-diego-cell'
# ---------------------------------------
- type: replace
  path: /variables/name=blobstore_tls/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-singleton-blobstore'
- type: replace
  path: /variables/name=blobstore_tls/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-singleton-blobstore.{{ .Release.Namespace }}'
# ---------------------------------------
- type: replace
  path: /variables/name=diego_auctioneer_client/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-diego-api'
# ---------------------------------------
- type: replace
  path: /variables/name=diego_auctioneer_server/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-scheduler'
# ---------------------------------------
- type: replace
  path: /variables/name=diego_bbs_client/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-diego-cell'
# ---------------------------------------
- type: replace
  path: /variables/name=diego_bbs_server/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-diego-api'
- type: replace
  path: /variables/name=diego_bbs_server/options?/alternative_names?/-
  value: '127.0.0.1'
- type: replace
  path: /variables/name=diego_bbs_server/options?/alternative_names?/-
  # TODO: loop through replica count/az count, not just ordinal 0 (using helm templating)
  value: '{{ .Values.deployment_name }}-diego-api-0'
# ---------------------------------------
- type: replace
  path: /variables/name=diego_rep_client/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-diego-api'
# ---------------------------------------
- type: replace
  path: /variables/name=diego_rep_agent_v2/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-diego-cell'
# ---------------------------------------
- type: replace
  path: /variables/name=loggregator_tls_statsdinjector/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-uaa'
# ---------------------------------------
- type: replace
  path: /variables/name=loggregator_tls_doppler/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-doppler'
# ---------------------------------------
- type: replace
  path: /variables/name=loggregator_tls_doppler/options?/alternative_names?/-
  value: 'metron'
# ---------------------------------------
- type: replace
  path: /variables/name=loggregator_tls_tc/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-log-api'
# ---------------------------------------
- type: replace
  path: /variables/name=loggregator_tls_cc_tc/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-log-api'
# ---------------------------------------
- type: replace
  path: /variables/name=loggregator_rlp_gateway_tls_cc/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-log-api'
# ---------------------------------------
- type: replace
  path: /variables/name=loggregator_tls_rlp/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-log-api'
# ---------------------------------------
- type: replace
  path: /variables/name=loggregator_rlp_gateway/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-log-api'
# ---------------------------------------
- type: replace
  path: /variables/name=adapter_rlp_tls/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-adapter'
# ---------------------------------------
- type: replace
  path: /variables/name=scheduler_api_tls/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-scheduler'
# ---------------------------------------
- type: replace
  path: /variables/name=adapter_tls/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-adapter'
# ---------------------------------------
- type: replace
  path: /variables/name=scheduler_client_tls/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-scheduler'
# ---------------------------------------
- type: replace
  path: /variables/name=logs_provider/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-doppler'
# ---------------------------------------
- type: replace
  path: /variables/name=log_cache/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-doppler'
- type: replace
  path: /variables/name=log_cache/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-scheduler'
# ---------------------------------------
- type: replace
  path: /variables/name=log_cache_to_loggregator_agent/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-scheduler'
- type: replace
  path: /variables/name=log_cache_to_loggregator_agent/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-doppler'
# ---------------------------------------
- type: replace
  path: /variables/name=cc_logcache_tls/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-api'
# ---------------------------------------
- type: replace
  path: /variables/name=logcache_ssl/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-doppler'
# ---------------------------------------
- type: replace
  path: /variables/name=router_ssl/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-router'
# ---------------------------------------
- type: replace
  path: /variables/name=uaa_ssl/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-uaa'
# ---------------------------------------
- type: replace
  path: /variables/name=uaa_login_saml/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-uaa'
# ---------------------------------------
- type: replace
  path: /variables/name=cc_tls/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-api'
# ---------------------------------------
- type: replace
  path: /variables/name=cc_public_tls/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-api'
# ---------------------------------------
- type: replace
  path: /variables/name=cc_tls/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-api.{{ .Release.Namespace }}'
# ---------------------------------------
- type: replace
  path: /variables/name=cc_public_tls/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-api.{{ .Release.Namespace }}'
# ---------------------------------------
- type: replace
  path: /variables/name=cc_bridge_tps/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-scheduler'
# ---------------------------------------
- type: replace
  path: /variables/name=cc_bridge_cc_uploader/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-api'
# ---------------------------------------
- type: replace
  path: /variables/name=cc_bridge_cc_uploader_server/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-api'
- type: replace
  path: /variables/name=cc_bridge_cc_uploader_server/options?/alternative_names?/-
  value: '127.0.0.1'
- type: replace
  path: /variables/name=cc_bridge_cc_uploader_server/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-api.{{ .Release.Namespace }}'

# ---------------------------------------
- type: replace
  path: /variables/name=diego_locket_server/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-diego-api'
# ---------------------------------------
- type: replace
  path: /variables/name=diego_locket_client/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-api'
# ---------------------------------------
- type: replace
  path: /variables/name=gorouter_backend_tls/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-router'
# ---------------------------------------
- type: replace
  path: /variables/name=ssh_proxy_backends_tls/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-scheduler'
# ---------------------------------------
- type: replace
  path: /variables/name=mysql_server_certificate/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-database'
# ---------------------------------------
- type: replace
  path: /variables/name=loggregator_rlp_gateway_tls/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-log-api'
# ---------------------------------------
- type: replace
  path: /variables/name=loggregator_trafficcontroller_tls/options?/alternative_names?/-
  value: '{{ .Values.deployment_name }}-log-api'
# ---------------------------------------
- type: replace
  path: /variables/name=network_policy_server/options?/alternative_names?/-
  value: '*.{{ .Values.deployment_name }}-api'
# ---------------------------------------
- type: replace
  path: /variables/name=network_policy_client/options?/alternative_names?/-
  value: '*.{{ .Values.deployment_name }}-diego-cell'
# ---------------------------------------
- type: replace
  path: /variables/name=blobstore_tls/options?/alternative_names?/-
  value: '*.{{ .Values.deployment_name }}-singleton-blobstore'
- type: replace
  path: /variables/name=blobstore_tls/options?/alternative_names?/-
  value: '*.{{ .Values.deployment_name }}-singleton-blobstore.{{ .Release.Namespace }}'
# ---------------------------------------
- type: replace
  path: /variables/name=diego_auctioneer_client/options?/alternative_names?/-
  value: '*.{{ .Values.deployment_name }}-diego-api'
# ---------------------------------------
- type: replace
  path: /variables/name=diego_auctioneer_server/options?/alternative_names?/-
  value: '*.{{ .Values.deployment_name }}-scheduler'
# ---------------------------------------
- type: replace
  path: /variables/name=diego_bbs_client/options?/alternative_names?/-
  value: '*.{{ .Values.deployment_name }}-diego-cell'
# ---------------------------------------
- type: replace
  path: /variables/name=diego_bbs_server/options?/alternative_names?/-
  value: '*.{{ .Values.deployment_name }}-diego-api'
# ---------------------------------------
- type: replace
  path: /variables/name=diego_rep_client/options?/alternative_names?/-
  value: '*.{{ .Values.deployment_name }}-diego-api'
# ---------------------------------------
- type: replace
  path: /variables/name=diego_rep_agent_v2/options?/alternative_names?/-
  value: '*.{{ .Values.deployment_name }}-diego-cell'
- type: replace
  path: /variables/name=diego_rep_agent_v2/options?/alternative_names?/-
  value: '127.0.0.1'
- type: replace
  path: /variables/name=diego_rep_agent_v2/options?/alternative_names?/-
  value: 'localhost'
# ---------------------------------------
- type: replace
  path: /variables/name=loggregator_tls_statsdinjector/options?/alternative_names?/-
  value: '*.{{ .Values.deployment_name }}-uaa'
# ---------------------------------------
- type: replace
  path: /variables/name=loggregator_tls_doppler/options?/alternative_names?/-
  value: '*.{{ .Values.deployment_name }}-doppler'
# ---------------------------------------
- type: replace
  path: /variables/name=loggregator_tls_tc/options?/alternative_names?/-
  value: '*.{{ .Values.deployment_name }}-log-api'
# ---------------------------------------
- type: replace
  path: /variables/name=loggregator_tls_cc_tc/options?/alternative_names?/-
  value: '*.{{ .Values.deployment_name }}-log-api'
# ---------------------------------------
- type: replace
  path: /variables/name=loggregator_rlp_gateway_tls_cc/options?/alternative_names?/-
  value: '*.{{ .Values.deployment_name }}-log-api'
# ---------------------------------------
- type: replace
  path: /variables/name=loggregator_tls_rlp/options?/alternative_names?/-
  value: '*.{{ .Values.deployment_name }}-log-api'
# ---------------------------------------
- type: replace
  path: /variables/name=loggregator_rlp_gateway/options?/alternative_names?/-
  value: '*.{{ .Values.deployment_name }}-log-api'
# ---------------------------------------
- type: replace
  path: /variables/name=adapter_rlp_tls/options?/alternative_names?/-
  value: '*.{{ .Values.deployment_name }}-adapter'
# ---------------------------------------
- type: replace
  path: /variables/name=scheduler_api_tls/options?/alternative_names?/-
  value: '*.{{ .Values.deployment_name }}-scheduler'
# ---------------------------------------
- type: replace
  path: /variables/name=adapter_tls/options?/alternative_names?/-
  value: '*.{{ .Values.deployment_name }}-adapter'
# ---------------------------------------
- type: replace
  path: /variables/name=scheduler_client_tls/options?/alternative_names?/-
  value: '*.{{ .Values.deployment_name }}-scheduler'
# ---------------------------------------
- type: replace
  path: /variables/name=logs_provider/options?/alternative_names?/-
  value: '*.{{ .Values.deployment_name }}-doppler'
# ---------------------------------------
- type: replace
  path: /variables/name=log_cache/options?/alternative_names?/-
  value: '*.{{ .Values.deployment_name }}-doppler'
- type: replace
  path: /variables/name=log_cache/options?/alternative_names?/-
  value: '*.{{ .Values.deployment_name }}-scheduler'
# ---------------------------------------
- type: replace
  path: /variables/name=log_cache_to_loggregator_agent/options?/alternative_names?/-
  value: '*.{{ .Values.deployment_name }}-scheduler'
- type: replace
  path: /variables/name=log_cache_to_loggregator_agent/options?/alternative_names?/-
  value: '*.{{ .Values.deployment_name }}-doppler'
# ---------------------------------------
- type: replace
  path: /variables/name=cc_logcache_tls/options?/alternative_names?/-
  value: '*.{{ .Values.deployment_name }}-api'
# ---------------------------------------
- type: replace
  path: /variables/name=logcache_ssl/options?/alternative_names?/-
  value: '*.{{ .Values.deployment_name }}-doppler'
# ---------------------------------------
- type: replace
  path: /variables/name=router_ssl/options?/alternative_names?/-
  value: '*.{{ .Values.deployment_name }}-router'
# ---------------------------------------
- type: replace
  path: /variables/name=uaa_ssl/options?/alternative_names?/-
  value: '*.{{ .Values.deployment_name }}-uaa'
# ---------------------------------------
- type: replace
  path: /variables/name=uaa_login_saml/options?/alternative_names?/-
  value: '*.{{ .Values.deployment_name }}-uaa'
# ---------------------------------------
- type: replace
  path: /variables/name=cc_tls/options?/alternative_names?/-
  value: '*.{{ .Values.deployment_name }}-api'
# ---------------------------------------
- type: replace
  path: /variables/name=cc_public_tls/options?/alternative_names?/-
  value: '*.{{ .Values.deployment_name }}-api'
# ---------------------------------------
- type: replace
  path: /variables/name=cc_bridge_tps/options?/alternative_names?/-
  value: '*.{{ .Values.deployment_name }}-scheduler'
# ---------------------------------------
- type: replace
  path: /variables/name=cc_bridge_cc_uploader/options?/alternative_names?/-
  value: '*.{{ .Values.deployment_name }}-api'
# ---------------------------------------
- type: replace
  path: /variables/name=cc_bridge_cc_uploader_server/options?/alternative_names?/-
  value: '*.{{ .Values.deployment_name }}-api'
# ---------------------------------------
- type: replace
  path: /variables/name=diego_locket_server/options?/alternative_names?/-
  value: '*.{{ .Values.deployment_name }}-diego-api'
- type: replace
  path: /variables/name=diego_locket_server/options?/alternative_names?/-
  value: '127.0.0.1'
# ---------------------------------------
- type: replace
  path: /variables/name=diego_locket_client/options?/alternative_names?/-
  value: '*.{{ .Values.deployment_name }}-api'
# ---------------------------------------
- type: replace
  path: /variables/name=gorouter_backend_tls/options?/alternative_names?/-
  value: '*.{{ .Values.deployment_name }}-router'
# ---------------------------------------
- type: replace
  path: /variables/name=ssh_proxy_backends_tls/options?/alternative_names?/-
  value: '*.{{ .Values.deployment_name }}-scheduler'
# ---------------------------------------
- type: replace
  path: /variables/name=mysql_server_certificate/options?/alternative_names?/-
  value: '*.{{ .Values.deployment_name }}-database'
# ---------------------------------------
- type: replace
  path: /variables/name=loggregator_rlp_gateway_tls/options?/alternative_names?/-
  value: '*.{{ .Values.deployment_name }}-log-api'
# ---------------------------------------
- type: replace
  path: /variables/name=loggregator_trafficcontroller_tls/options?/alternative_names?/-
  value: '*.{{ .Values.deployment_name }}-log-api'
