# This ops file sets the openSUSE stemcells.

- type: replace
  path: /stemcells/alias=default/os
  value: opensuse-42.3

- type: replace
  path: /stemcells/alias=default/version
  value: 30.g9c91e77-30.80-7.0.0_257.gb97ced55

- type: replace
  path: /addons/name=loggregator_agent/include/stemcell/os=ubuntu-xenial/os
  value: opensuse-42.3

- type: replace
  path: /addons/name=forwarder_agent/include/stemcell/os=ubuntu-xenial/os
  value: opensuse-42.3

- type: replace
  path: /addons/name=bpm/include/stemcell/os=ubuntu-xenial/os
  value: opensuse-42.3
