# We make the decision here, because this file needs to be applied last
{{if eq .Values.features.eirini true}}

# Disable Diego

# Remove the whole diego-cell instance group
- type: remove
  path: /instance_groups/name=diego-cell


# Remove bbs and silk-controller from diego-api
# TODO: remove bbs in the future - when the clock and worker no longer need it
# - type: remove
#   path: /instance_groups/name=diego-api/jobs/name=bbs

# Remove from auctioneer, tps and ssh_proxy from scheduler
- type: remove
  path: /instance_groups/name=scheduler/jobs/name=auctioneer
- type: remove
  path: /instance_groups/name=scheduler/jobs/name=tps
- type: remove
  path: /instance_groups/name=scheduler/jobs/name=ssh_proxy
{{end}}
