# This is a temporary file used for selectively removing variables during the initial development.
# It should go away once all instance_groups work properly with cf-operator.

- type: remove
  path: /variables/name=blobstore_admin_users_password
- type: remove
  path: /variables/name=blobstore_secure_link_secret
- type: remove
  path: /variables/name=cc_bulk_api_password
- type: remove
  path: /variables/name=cc_db_encryption_key
- type: remove
  path: /variables/name=cc_internal_api_password
- type: remove
  path: /variables/name=cc_staging_upload_password
- type: remove
  path: /variables/name=cf_mysql_mysql_admin_password
- type: remove
  path: /variables/name=cf_mysql_mysql_cluster_health_password
- type: remove
  path: /variables/name=cf_mysql_mysql_galera_healthcheck_endpoint_password
- type: remove
  path: /variables/name=cf_mysql_mysql_galera_healthcheck_password
- type: remove
  path: /variables/name=cf_mysql_proxy_api_password
- type: remove
  path: /variables/name=cc_database_password
- type: remove
  path: /variables/name=credhub_database_password
- type: remove
  path: /variables/name=diego_database_password
- type: remove
  path: /variables/name=uaa_database_password
- type: remove
  path: /variables/name=routing_api_database_password
- type: remove
  path: /variables/name=network_policy_database_password
- type: remove
  path: /variables/name=network_connectivity_database_password
- type: remove
  path: /variables/name=uaa_default_encryption_passphrase
- type: remove
  path: /variables/name=silk_ca
- type: remove
  path: /variables/name=silk_controller
- type: remove
  path: /variables/name=silk_daemon
- type: remove
  path: /variables/name=network_policy_ca
- type: remove
  path: /variables/name=network_policy_server
- type: remove
  path: /variables/name=network_policy_client
- type: remove
  path: /variables/name=uaa_clients_routing_api_client_secret
- type: remove
  path: /variables/name=uaa_clients_tcp_emitter_secret
- type: remove
  path: /variables/name=router_status_password
- type: remove
  path: /variables/name=cf_admin_password
- type: remove
  path: /variables/name=cf_bosh_password
- type: remove
  path: /variables/name=router_route_services_secret
- type: remove
  path: /variables/name=uaa_admin_client_secret
- type: remove
  path: /variables/name=uaa_clients_cc-routing_secret
- type: remove
  path: /variables/name=uaa_clients_cc-service-dashboards_secret
- type: remove
  path: /variables/name=uaa_clients_cc_service_key_client_secret
- type: remove
  path: /variables/name=uaa_clients_cf_smoke_tests_secret
- type: remove
  path: /variables/name=uaa_clients_cloud_controller_username_lookup_secret
- type: remove
  path: /variables/name=uaa_clients_doppler_secret
- type: remove
  path: /variables/name=uaa_clients_gorouter_secret
- type: remove
  path: /variables/name=uaa_clients_network_policy_secret
- type: remove
  path: /variables/name=uaa_clients_ssh-proxy_secret
- type: remove
  path: /variables/name=uaa_clients_tcp_router_secret
- type: remove
  path: /variables/name=diego_bbs_encryption_keys_passphrase
- type: remove
  path: /variables/name=credhub_encryption_password
- type: remove
  path: /variables/name=credhub_admin_client_secret
- type: remove
  path: /variables/name=diego_ssh_proxy_host_key
- type: remove
  path: /variables/name=uaa_jwt_signing_key
- type: remove
  path: /variables/name=service_cf_internal_ca
- type: remove
  path: /variables/name=blobstore_tls
- type: remove
  path: /variables/name=diego_auctioneer_client
- type: remove
  path: /variables/name=diego_auctioneer_server
- type: remove
  path: /variables/name=diego_bbs_client
- type: remove
  path: /variables/name=diego_bbs_server
- type: remove
  path: /variables/name=diego_rep_client
- type: remove
  path: /variables/name=diego_rep_agent_v2
- type: remove
  path: /variables/name=loggregator_tls_statsdinjector
- type: remove
  path: /variables/name=loggregator_tls_doppler
- type: remove
  path: /variables/name=loggregator_tls_tc
- type: remove
  path: /variables/name=loggregator_tls_cc_tc
- type: remove
  path: /variables/name=loggregator_rlp_gateway_tls_cc
- type: remove
  path: /variables/name=loggregator_tls_rlp
- type: remove
  path: /variables/name=loggregator_rlp_gateway
- type: remove
  path: /variables/name=adapter_rlp_tls
- type: remove
  path: /variables/name=scheduler_api_tls
- type: remove
  path: /variables/name=adapter_tls
- type: remove
  path: /variables/name=scheduler_client_tls
- type: remove
  path: /variables/name=logs_provider
- type: remove
  path: /variables/name=log_cache_ca
- type: remove
  path: /variables/name=log_cache
- type: remove
  path: /variables/name=log_cache_to_loggregator_agent
- type: remove
  path: /variables/name=cc_logcache_tls
- type: remove
  path: /variables/name=logcache_ssl
- type: remove
  path: /variables/name=router_ca
- type: remove
  path: /variables/name=router_ssl
- type: remove
  path: /variables/name=uaa_ca
- type: remove
  path: /variables/name=uaa_ssl
- type: remove
  path: /variables/name=uaa_login_saml
- type: remove
  path: /variables/name=cc_tls
- type: remove
  path: /variables/name=cc_public_tls
- type: remove
  path: /variables/name=cc_bridge_tps
- type: remove
  path: /variables/name=cc_bridge_cc_uploader
- type: remove
  path: /variables/name=cc_bridge_cc_uploader_server
- type: remove
  path: /variables/name=diego_locket_server
- type: remove
  path: /variables/name=diego_locket_client
- type: remove
  path: /variables/name=locket_database_password
- type: remove
  path: /variables/name=application_ca
- type: remove
  path: /variables/name=diego_instance_identity_ca
- type: remove
  path: /variables/name=gorouter_backend_tls
- type: remove
  path: /variables/name=credhub_ca
- type: remove
  path: /variables/name=credhub_tls
- type: remove
  path: /variables/name=ssh_proxy_backends_tls
- type: remove
  path: /variables/name=pxc_galera_ca
- type: remove
  path: /variables/name=pxc_server_ca
- type: remove
  path: /variables/name=galera_server_certificate
- type: remove
  path: /variables/name=mysql_server_certificate
- type: remove
  path: /variables/name=loggregator_rlp_gateway_tls
- type: remove
  path: /variables/name=loggregator_trafficcontroller_tls
