# This is a temporary file used for selectively removing instance_groups during the initial
# development. It should go away once all instance_groups work properly with cf-operator.

- type: remove
  path: /instance_groups/name=tcp-router
- type: remove
  path: /instance_groups/name=credhub
- type: remove
  path: /instance_groups/name=rotate-cc-database-key
