{{- $root := . -}}
---
apiVersion: fissile.cloudfoundry.org/v1alpha1
kind: BOSHDeployment
metadata:
  name: {{ .Values.deployment_name }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/name: {{ include "kubecf.fullname" . }}
    app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
    helm.sh/chart: {{ include "kubecf.chart" . }}
spec:
  manifest:
    name: cf-deployment
    type: configmap
  ops:
{{- if .Values.features.suse_buildpacks }}
{{- range $path, $bytes := .Files.Glob "assets/operations/buildpacks/*" }}
  - name: {{ include "kubecf.ops-name" $path }}
    type: configmap
{{- end }}
{{- end }}
{{- if .Values.features.eirini.enabled }}
  - name: ops-use-bits-service
    type: configmap
{{- end }}
{{- range $path, $bytes := .Files.Glob "assets/operations/instance_groups/*" }}
  - name: {{ include "kubecf.ops-name" $path }}
    type: configmap
{{- end }}
{{- range $path, $bytes := .Files.Glob "assets/operations/temporary/*" }}
  - name: {{ include "kubecf.ops-name" $path }}
    type: configmap
{{- end }}
{{- if not .Values.sizing.HA }}
  - name: ops-single-availability
    type: configmap
{{- end }}
{{- range $path, $bytes := .Files.Glob "assets/operations/*" }}
  - name: {{ include "kubecf.ops-name" $path }}
    type: configmap
{{- end }}
{{- if .Values.features.eirini.enabled }}
  - name: ops-remove-diego
    type: configmap
{{- end }}
{{- range $_, $ops := .Values.operations.custom }}
  - name: {{ $ops | quote }}
    type: configmap
{{- end }}
  - name: user-provided-properties
    type: configmap
