{{- if not .Values.features.multiple_cluster.control_plane.enabled  }}
{{- if .Values.features.multiple_cluster.cell_segment.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.features.multiple_cluster_mode.control_plane_workers.uaa.name }}
spec:
  clusterIP: None
  type: ClusterIP

---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.features.multiple_cluster_mode.control_plane_workers.uaa.name }}
subsets:
- addresses:
  {{- range .Values.features.multiple_cluster_mode.control_plane_workers.uaa.addresses }}
    - ip: {{ .ip }}
  {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.features.multiple_cluster_mode.control_plane_workers.diego_api.name }}
spec:
  clusterIP: None
  type: ClusterIP

---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.features.multiple_cluster_mode.control_plane_workers.diego_api.name }}
subsets:
- addresses:
  {{- range .Values.features.multiple_cluster_mode.control_plane_workers.diego_api.addresses }}
    - ip: {{ .ip }}
  {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.features.multiple_cluster_mode.control_plane_workers.api.name }} 
spec:
  clusterIP: None
  type: ClusterIP

---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.features.multiple_cluster_mode.control_plane_workers.api.name }} 
subsets:
- addresses:
  {{- range .Values.features.multiple_cluster_mode.control_plane_workers.api.addresses }}
    - ip: {{ .ip }}
  {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.features.multiple_cluster_mode.control_plane_workers.singleton_blobstore.name }} 
spec:
  clusterIP: None
  type: ClusterIP

---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.features.multiple_cluster_mode.control_plane_workers.singleton_blobstore.name }}
subsets:
- addresses:
  {{- range .Values.features.multiple_cluster_mode.control_plane_workers.singleton_blobstore.addresses }}
    - ip: {{ .ip }}
  {{- end }}
{{- end }}
{{- end }}
