# This template creates a ConfigMap for each ops file under assets/operations.
{{- define "kubecf.ops" -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubecf.ops-name" .Path }}
  labels:
    app.kubernetes.io/component: operations
    app.kubernetes.io/instance: {{ .Root.Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Root.Release.Service | quote }}
    app.kubernetes.io/name: {{ include "kubecf.fullname" .Root }}
    app.kubernetes.io/version: {{ default .Root.Chart.Version .Root.Chart.AppVersion | quote }}
    helm.sh/chart: {{ include "kubecf.chart" .Root }}
data:
  ops: |-
    {{- tpl (.Root.Files.Get .Path) .Root | nindent 4 -}}
{{- end -}}

{{- $root := . -}}
{{- if .Values.features.suse_buildpacks }}
{{ include "kubecf.ops" (dict "Root" $root "Path" "assets/operations/buildpacks/set_suse_buildpacks.yaml") }}
{{- end }}
{{- range $path, $bytes := .Files.Glob "assets/operations/instance_groups/*" }}
{{ include "kubecf.ops" (dict "Root" $root "Path" $path) }}
{{- end }}
{{- range $path, $bytes := .Files.Glob "assets/operations/temporary/*" }}
{{ include "kubecf.ops" (dict "Root" $root "Path" $path) }}
{{- end }}
{{- range $path, $bytes := .Files.Glob "assets/operations/*" }}
{{ include "kubecf.ops" (dict "Root" $root "Path" $path) }}
{{- end }}
