{{- /*
  Template "scf.implicit-var" generates the kube secret declaration for a
  variable.  It takes a list of two arguments: the context, and the variable
  name.
*/ -}}
{{- define "scf.implicit-var" }}
{{- $variable_name := (last .) }}
{{- with (first .) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.deployment_name }}.var-{{ $variable_name | replace "_" "-" | replace "." "-" }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/name: {{ include "scf.fullname" . }}
    app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
    helm.sh/chart: {{ include "scf.chart" . }}
type: Opaque
stringData:
  value: {{ template "scf.dig" (list .Values ( splitList "." $variable_name )) }}
{{- end }}
{{- end }}

{{ include "scf.implicit-var" (list . "system_domain") }}
{{ include "scf.implicit-var" (list . "deployment_name") }}
{{ include "scf.implicit-var" (list . "releases.defaults.url") }}
{{ include "scf.implicit-var" (list . "stemcell.os") }}
{{ include "scf.implicit-var" (list . "stemcell.version") }}
