- path: /releases/-
  type: replace
  value:
    name: cf-acceptance-tests
    url: {{ include "kubecf.releaseURLLookup" (list .Values.releases "cf-acceptance-tests") }}
    version: 0.0.6
    stemcell: {{ include "kubecf.stemcellLookup" (list .Values.releases "cf-acceptance-tests") }}

- path: /instance_groups/-
  type: replace
  value:
    azs:
    - z1
    instances: 1
    jobs:
    - name: acceptance-tests
      properties:
        acceptance_tests:
          admin_password: ((cf_admin_password))
          admin_user: admin
          api: api.((system_domain))
          apps_domain: ((system_domain))
          skip_ssl_validation: true
        bpm:
          enabled: true
      release: cf-acceptance-tests
    lifecycle: errand
    name: acceptance-tests
    networks:
    - name: default
    stemcell: default
    update:
      serial: true
    vm_type: minimal
