{{- if .Values.features.suse_buildpacks.enabled }}
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/stacks/-
  value:
    name: sle15
    description: "SUSE Linux Enterprise-based filesystem"

- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/diego/lifecycle_bundles?
  value:
    buildpack/sle15: buildpack_app_lifecycle/buildpack_app_lifecycle.tgz
    buildpack/cflinuxfs3: buildpack_app_lifecycle/buildpack_app_lifecycle.tgz
    docker: docker_app_lifecycle/docker_app_lifecycle.tgz
{{- end }}

{{- $path := "/var/vcap/data/shared-packages/" }}
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/install_buildpacks
  value:
  ## Order is important here
  - name: staticfile_buildpack
    file: {{ $path }}staticfile-buildpack/packages/staticfile-buildpack-cflinuxfs3/staticfile_buildpack-cflinuxfs3-v1.5.3.zip
  - name: java_buildpack
    file: {{ $path }}java-buildpack/packages/java-buildpack-cflinuxfs3/java-buildpack-cflinuxfs3-v4.26.zip
  - name: ruby_buildpack
    file: {{ $path }}ruby-buildpack/packages/ruby-buildpack-cflinuxfs3/ruby_buildpack-cflinuxfs3-v1.8.8.zip
  - name: dotnet-core_buildpack
    file: {{ $path }}dotnet-core-buildpack/packages/dotnet-core-buildpack-cflinuxfs3/dotnet-core_buildpack-cflinuxfs3-v2.3.4.zip
  - name: nodejs_buildpack
    file: {{ $path }}nodejs-buildpack/packages/nodejs-buildpack-cflinuxfs3/nodejs_buildpack-cflinuxfs3-v1.7.9.zip
  - name: go_buildpack
    file: {{ $path }}go-buildpack/packages/go-buildpack-cflinuxfs3/go_buildpack-cflinuxfs3-v1.9.5.zip
  - name: python_buildpack
    file: {{ $path }}python-buildpack/packages/python-buildpack-cflinuxfs3/python_buildpack-cflinuxfs3-v1.7.6.zip
  - name: php_buildpack
    file: {{ $path }}php-buildpack/packages/php-buildpack-cflinuxfs3/php_buildpack-cflinuxfs3-v4.4.6.zip
  - name: nginx_buildpack
    file: {{ $path }}nginx-buildpack/packages/nginx-buildpack-cflinuxfs3/nginx_buildpack-cflinuxfs3-v1.1.4.zip
  - name: r_buildpack
    file: {{ $path }}r-buildpack/packages/r-buildpack-cflinuxfs3/r_buildpack-cflinuxfs3-v1.1.1.zip
  - name: binary_buildpack
    file: {{ $path }}binary-buildpack/packages/binary-buildpack-cflinuxfs3/binary_buildpack-cflinuxfs3-v1.0.36.zip
{{- if .Values.features.suse_buildpacks.enabled }}
  - name: staticfile_buildpack
    file: {{ $path }}{{ (index .Values.releases "suse-staticfile-buildpack").file }}
  - name: java_buildpack
    file: {{ $path }}{{ (index .Values.releases "suse-java-buildpack").file }}
  - name: ruby_buildpack
    file: {{ $path }}{{ (index .Values.releases "suse-ruby-buildpack").file }}
  - name: dotnet-core_buildpack
    file: {{ $path }}{{ (index .Values.releases "suse-dotnet-core-buildpack").file }}
  - name: nodejs_buildpack
    file: {{ $path }}{{ (index .Values.releases "suse-nodejs-buildpack").file }}
  - name: go_buildpack
    file: {{ $path }}{{ (index .Values.releases "suse-go-buildpack").file }}
  - name: python_buildpack
    file: {{ $path }}{{ (index .Values.releases "suse-python-buildpack").file }}
  - name: php_buildpack
    file: {{ $path }}{{ (index .Values.releases "suse-php-buildpack").file }}
  - name: nginx_buildpack
    file: {{ $path }}{{ (index .Values.releases "suse-nginx-buildpack").file }}
  - name: binary_buildpack
    file: {{ $path }}{{ (index .Values.releases "suse-binary-buildpack").file }}
{{- end }}

{{- if .Values.features.credhub.enabled }}
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/credhub_api?/external_url
  value: https://credhub.((system_domain))
{{- end }}

# These operations set the default values explicitly in order to get the rotate-cc-database-key
# errand working. Without them, the rotate-cc-database-key errand is not able to resolve the CC BOSH
# link correctly.
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/ccdb/max_connections?
  value: 25
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/ccdb/pool_timeout?
  value: 10
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/ccdb/ssl_verify_hostname?
  value: true
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/ccdb/read_timeout?
  value: 3600
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/ccdb/connection_validation_timeout?
  value: 3600

{{- range $keyLabel := .Values.ccdb.encryption.rotation.key_labels }}
{{- if not (regexMatch "^[a-z]+[a-z0-9_]*[a-z0-9]+$" $keyLabel) }}
{{ fail "One or more items in ccdb.encryption.rotation.key_labels don't match the regex /^[a-z]+[a-z0-9_]*[a-z0-9]+$/" }}
{{- end }}
{{- if gt (len $keyLabel) 240 }}
{{ fail "One or more items in ccdb.encryption.rotation.key_labels exceed the maximum length of 240 characters" }}
{{- end }}
- type: replace
  path: /variables/-
  value:
    name: "ccdb_key_label_{{ $keyLabel }}"
    type: password
{{- end }}
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/database_encryption?
  value: &encryption_info
    keys:
      {{- range $keyLabel := .Values.ccdb.encryption.rotation.key_labels }}
      ccdb_key_label_{{ $keyLabel }}: "((ccdb_key_label_{{ $keyLabel }}))"
      {{- end }}
    current_key_label: "ccdb_key_label_{{ .Values.ccdb.encryption.rotation.current_key_label }}"
- type: replace
  path: /instance_groups/name=cc-worker/jobs/name=cloud_controller_worker/properties/cc/database_encryption?
  value: *encryption_info
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/cc/database_encryption?
  value: *encryption_info

# core_file_pattern should be disabled as CC is not running on a VM.
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/core_file_pattern?
  value: false

# Disable tuning /proc/sys kernel parameters as file_server is running on a container.
- type: replace
  path: /instance_groups/name=api/jobs/name=file_server/properties/set_kernel_parameters?
  value: false

# We don't have a /var/vcap/job/*/packages directory, so we point to all the packages.
- type: replace
  path: /instance_groups/name=api/jobs/name=file_server/properties/diego?/file_server/static_directory
  value: "/var/vcap/packages/"

# Enable volume services
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/volume_services_enabled?
  value: true

# Add empty BPM processes to buildpacks.
- type: replace
  path: /instance_groups/name=api/jobs/name=binary-buildpack/properties?/quarks/bpm/processes
  value: []
- type: replace
  path: /instance_groups/name=api/jobs/name=dotnet-core-buildpack/properties?/quarks/bpm/processes
  value: []
- type: replace
  path: /instance_groups/name=api/jobs/name=go-buildpack/properties?/quarks/bpm/processes
  value: []
- type: replace
  path: /instance_groups/name=api/jobs/name=java-buildpack/properties?/quarks/bpm/processes
  value: []
- type: replace
  path: /instance_groups/name=api/jobs/name=nodejs-buildpack/properties?/quarks/bpm/processes
  value: []
- type: replace
  path: /instance_groups/name=api/jobs/name=nginx-buildpack/properties?/quarks/bpm/processes
  value: []
- type: replace
  path: /instance_groups/name=api/jobs/name=r-buildpack/properties?/quarks/bpm/processes
  value: []
- type: replace
  path: /instance_groups/name=api/jobs/name=php-buildpack/properties?/quarks/bpm/processes
  value: []
- type: replace
  path: /instance_groups/name=api/jobs/name=python-buildpack/properties?/quarks/bpm/processes
  value: []
- type: replace
  path: /instance_groups/name=api/jobs/name=ruby-buildpack/properties?/quarks/bpm/processes
  value: []
- type: replace
  path: /instance_groups/name=api/jobs/name=staticfile-buildpack/properties?/quarks/bpm/processes
  value: []

# Add quarks properties for cloud_controller_ng.
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/quarks?
  value:
    ports:
    - name: api
      protocol: TCP
      internal: 9022
    - name: api-tls
      protocol: TCP
      internal: 9023
    - name: api-mutual-tls
      protocol: TCP
      internal: 9024
    run:
      healthcheck:
        ccng_monit_http_healthcheck:
          readiness:
            # This job exists just to healthcheck cloud_controller_ng; we're
            # already doing that separately.
            exec:
              command: [/bin/true]
          liveness:
            exec:
              command:
              - /usr/bin/pgrep
              - --full
              - --exact
              - bash /var/vcap/jobs/cloud_controller_ng/bin/ccng_monit_http_healthcheck
        cloud_controller_ng:
          readiness: &cloud_controller_ng_readiness
            exec:
              command: [curl, --fail, --head, --silent, --unix-socket, /var/vcap/data/cloud_controller_ng/cloud_controller.sock, http:/healthz]
          # We don't want a liveness probe here as we do migration here, and we
          # do not want to interrupt that.  We may want to consider using a
          # startupProbe in the future (once that feature stabilizes).
          liveness: ~
        local_worker_1:
          readiness: &cc_local_worker_readiness
            exec:
              command: [/usr/bin/pgrep, --full, cc_api_worker]
        local_worker_2:
          readiness: *cc_local_worker_readiness
        nginx:
          readiness:
            httpGet:
              httpHeaders:
              - name: Host
                value: api
              path: /healthz
              port: 9024
              scheme: HTTPS
          liveness:
            exec:
              command: [/usr/bin/pgrep, --full, "nginx: master process"]
    post_start:
      condition:
        exec:
          command: [curl, --fail, --head, --silent, http://127.0.0.1:9022/healthz]

# Add quarks properties for cc_uploader.
- type: replace
  path: /instance_groups/name=api/jobs/name=cc_uploader/properties/quarks?
  value:
    ports:
    - name: http
      protocol: TCP
      internal: 9090
    - name: https
      protocol: TCP
      internal: 9091
    run:
      healthcheck:
        cc_uploader:
          readiness:
            # cc-uploader does not have a health check endpoint; just use a TCP
            # socket.
            tcpSocket:
              port: 9091

# Add quarks properties for file_server.
- type: replace
  path: /instance_groups/name=api/jobs/name=file_server/properties/quarks?
  value:
    ports:
    - name: file-server
      protocol: TCP
      internal: &file-server-port 8080
    run:
      healthcheck:
        file_server:
          readiness:
            httpGet:
              path: /v1/static/file_server/bin/file-server
              port: *file-server-port

# Add quarks properties for statsd_injector.
- type: replace
  path: /instance_groups/name=api/jobs/name=statsd_injector/properties/quarks?/run/healthcheck/statsd_injector/readiness/exec/command
  value:
  - /bin/sh
  - -c
  - ss -nlu src localhost:8125 | grep :8125

# Add quarks properties for policy-server.
- type: replace
  path: /instance_groups/name=api/jobs/name=policy-server/properties/quarks?
  value:
    ports:
    - name: policy-server
      protocol: TCP
      internal: 4002
    run:
      healthcheck:
        policy-server:
          readiness:
            httpGet:
              port: 4002
              scheme: HTTPS
    post_start:
      condition:
        exec:
          # policy-server doesn't support HTTP HEAD requests
          command: [curl, --insecure, --fail, --silent, https://localhost:4002/]

# Add quarks properties for policy-server-internal.
- type: replace
  path: /instance_groups/name=api/jobs/name=policy-server-internal/properties/quarks?
  value:
    run:
      healthcheck:
        policy-server-internal:
          readiness: &policy_server_internal_readiness
            httpGet:
              port: 31946
    post_start:
      condition:
        exec:
          # policy-server-internal doesn't support HTTP HEAD requests
          command: [curl, --fail, --silent, http://localhost:31946/]

- type: replace
  path: /instance_groups/name=api/jobs/name=route_registrar/properties/quarks?/run/healthcheck/route_registrar
  value:
    readiness: ~
      # The route registrar doesn't expose anything to indicate if the
      # routes are healthy

- type: replace
  path: /instance_groups/name=api/jobs/name=loggr-udp-forwarder/properties/quarks?/run/healthcheck/loggr-udp-forwarder/readiness/exec/command
  value: [sh, -c, ss -nlu sport = 3457 | grep :3457]

{{- $root := . -}}
{{- if .Values.features.suse_buildpacks.enabled }}
{{- range $path, $bytes := .Files.Glob "assets/operations/pre_render_scripts/api_*" }}
{{ $root.Files.Get $path }}
{{- end }}
{{- else }}
{{- range $path, $bytes := .Files.Glob "assets/operations/pre_render_scripts/api_*" }}
{{- if not (regexMatch "api_suse-.*?-buildpack" $path) }}
{{ $root.Files.Get $path }}
{{- end }}
{{- end }}
{{- end }}
