{{- if .Values.features.eirini.enabled -}}

- type: replace
  path: /releases/name=bits-service/version
  value: 2.28.0
- type: replace
  path: /releases/name=bits-service/url
  value: {{ .Values.releases.defaults.url | quote }}
- type: remove
  path: /releases/name=bits-service/sha1
- type: replace
  path: /releases/name=bits-service/stemcell?
  value: {{ include "kubecf.stemcellLookup" (list .Values.releases "bits-service") }}

# Add quarks information to the Bits Service jobs.
- type: replace
  path: /instance_groups/name=bits/jobs/name=bits-service/properties/quarks?
  value:
    ports:
    - name: bits-tls
      protocol: TCP
      internal: 443

- type: replace
  path: /variables/name=bits_service_ssl/options/serviceRef?/-
  value:
    name: {{ .Values.deployment_name }}-eirini-registry
    namespace: {{ .Release.Namespace }}
- type: replace
  path: /variables/name=bits_service_ssl/options/signer_type?
  value: cluster
- type: replace
  path: /variables/name=bits_service_ssl/options/alternative_names/-
  value: 127.0.0.1

# TODO: check to see where these should actually be public - what are the usecases?
- type: replace
  path: /instance_groups/name=bits/jobs/name=bits-service/properties/bits-service?/public_endpoint
  value: https://{{ .Values.deployment_name }}-bits.{{ .Release.Namespace }}

# Enable Docker registry on bits-service (used by OPI)
- type: replace
  path: /instance_groups/name=bits/jobs/name=bits-service/properties/bits-service/enable_registry?
  value: true
- type: replace
  path: /instance_groups/name=bits/jobs/name=bits-service/properties/bits-service/registry_endpoint?
  value: "https://127.0.0.1"
- type: replace
  path: /instance_groups/name=bits/jobs/name=bits-service/properties/bits-service/rootfs?/blobstore_type
  value: local

# Attach a persistent disk to bits-service VM to store eirinifs
- type: replace
  path: /instance_groups/name=bits/persistent_disk?
  value: 20480 # 20GB
{{- if .Values.kube.storage_class }}
- type: replace
  path: /instance_groups/name=bits/persistent_disk_type?
  value: {{ .Values.kube.storage_class }}
{{- end }}

- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/bits_service?/enabled?
  value: false
- type: replace
  path: /instance_groups/name=cc-worker/jobs/name=cloud_controller_worker/properties/cc/bits_service?/enabled?
  value: false
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/cc/bits_service?/enabled?
  value: false

{{- $root := . -}}
{{- range $path, $bytes := .Files.Glob "assets/operations/pre_render_scripts/bits_*" }}
{{ $root.Files.Get $path }}
{{- end }}

{{- end}}
