{{- include "_config.load" $ }}
{{- if .Values.features.eirini.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "eirini"
  namespace: {{ .Release.Namespace }}
data:
  opi.yml: |
    opi:
      app_namespace: {{ .Values.eirini.opi.namespace }}
      registry_address: "127.0.0.1:{{ .Values.bits.services.nodePort }}"
      registry_secret_name: {{ .Values.eirini.opi.registry_secret_name }}
      {{- $default_eirini_address := printf "https://eirini-opi.%s.svc:8085" .Release.Namespace }}
      eirini_address: {{ default $default_eirini_address .Values.eirini.opi.eirini_address }}

      {{- if .Values.eirini.opi.staging.downloader_image }}
      downloader_image: "{{ .Values.eirini.opi.staging.downloader_image }}:{{ .Values.eirini.opi.staging.downloader_image_tag }}"
      {{- else if .Values.eirini.opi.staging.downloader_image_tag }}
      downloader_image: "eirini/recipe-downloader:{{ .Values.eirini.opi.staging.downloader_image_tag }}"
      {{- else }}
      downloader_image: eirini/recipe-downloader@{{ .Files.Get "assets/versions/staging-downloader" }}
      {{- end }}

      {{- if .Values.eirini.opi.staging.executor_image }}
      executor_image: "{{ .Values.eirini.opi.staging.executor_image }}:{{ .Values.eirini.opi.staging.executor_image_tag }}"
      {{- else if .Values.eirini.opi.staging.executor_image_tag }}
      executor_image: "eirini/recipe-executor:{{ .Values.eirini.opi.staging.executor_image_tag }}"
      {{- else }}
      executor_image: eirini/recipe-executor@{{ .Files.Get "assets/versions/staging-executor" }}
      {{- end }}

      {{- if .Values.eirini.opi.staging.uploader_image }}
      uploader_image: "{{ .Values.eirini.opi.staging.uploader_image }}:{{ .Values.eirini.opi.staging.uploader_image_tag }}"
      {{- else if .Values.eirini.opi.staging.uploader_image_tag }}
      uploader_image: "eirini/recipe-uploader:{{ .Values.eirini.opi.staging.uploader_image_tag }}"
      {{- else }}
      uploader_image: eirini/recipe-uploader@{{ .Files.Get "assets/versions/staging-uploader" }}
      {{- end }}

      cc_uploader_secret_name: {{ .Values.eirini.opi.staging.tls.cc_uploader.secretName }}
      cc_uploader_cert_path: {{ .Values.eirini.opi.staging.tls.cc_uploader.certPath }}
      cc_uploader_key_path: {{ .Values.eirini.opi.staging.tls.cc_uploader.keyPath }}

      client_certs_secret_name: {{ .Values.eirini.opi.staging.tls.client.secretName }}
      client_cert_path: {{ .Values.eirini.opi.staging.tls.client.certPath }}
      client_key_path: {{ .Values.eirini.opi.staging.tls.client.keyPath }}

      ca_cert_secret_name: {{ .Values.eirini.opi.staging.tls.ca.secretName }}
      ca_cert_path: {{ .Values.eirini.opi.staging.tls.ca.path }}

      cc_cert_path: "/workspace/jobs/opi/secrets/cc.crt"
      cc_key_path: "/workspace/jobs/opi/secrets/cc.key"
      cc_ca_path: "/workspace/jobs/opi/secrets/cc.ca"
      # We really don't know the rootfs version...
      # rootfs_version: {{/* .Values.global.rootfs_version */}}
      client_ca_path: "/workspace/jobs/opi/secrets/eirini.ca"
      server_cert_path: "/workspace/jobs/opi/secrets/eirini-server.crt"
      server_key_path: "/workspace/jobs/opi/secrets/eirini-server.key"
      tls_port: 8085
      disk_limit_mb: {{ .Values.eirini.opi.disk_limit_mb }}
      application_service_account: eirini
      allow_run_image_as_root: false
  routing.yml: |
    app_namespace: {{ .Values.eirini.opi.namespace }}
    {{- $serviceName := .Values.eirini.opi.routing.nats.serviceName }}
    {{- if contains "." $serviceName | not }}
    {{- $serviceName = printf "%s.%s.svc" $serviceName .Release.Namespace }}
    {{- end }}
    nats_ip: {{ $serviceName }}
    nats_port: 4222
  metrics.yml: |
    app_namespace: {{ .Values.eirini.opi.namespace }}
    {{- $serviceName := .Values.eirini.opi.logs.serviceName }}
    {{- if contains "." $serviceName | not }}
    {{- $serviceName = printf "%s.%s.svc" $serviceName .Release.Namespace }}
    {{- end }}
    loggregator_address: "{{ $serviceName }}:8082"
    loggregator_cert_path: "/etc/eirini/secrets/doppler.crt"
    loggregator_key_path: "/etc/eirini/secrets/doppler.key"
    loggregator_ca_path: "/etc/eirini/secrets/doppler.ca"
  events.yml: |
    app_namespace: {{ .Values.eirini.opi.namespace }}
    {{- $serviceName := .Values.eirini.opi.cc_api.serviceName }}
    {{- if contains "." $serviceName | not }}
    {{- $serviceName = printf "%s.%s.svc" $serviceName .Release.Namespace }}
    {{- end }}
    cc_internal_api: "https://{{ $serviceName }}:9023"
    cc_cert_path: "/etc/eirini/secrets/cc.crt"
    cc_key_path: "/etc/eirini/secrets/cc.key"
    cc_ca_path: "/etc/eirini/secrets/cc.ca"
  staging-reporter.yml: |
    app_namespace: {{ .Values.eirini.opi.namespace }}
    eirini_cert_path: "/etc/eirini/secrets/eirini-client.crt"
    eirini_key_path: "/etc/eirini/secrets/eirini-client.key"
    ca_path: "/etc/eirini/secrets/eirini-client.ca"
{{- end }}
