name: Pull Request Tests
on:
  # Trigger the workflow when PRs are labeled
  pull_request_target:
    branches: [master]
    types: [labeled]

env:
  GIT_PAGER: cat

jobs:

  # The first thing we do is to check that the PR has the pr-test-trigger label
  # If it doesn't have it, the flow stops. If it does, we remove it (approval is good for one run only).
  dequeue:
    name: Dequeue
    if: contains(github.event.pull_request.labels.*.name, 'pr-test-trigger')
    runs-on: ubuntu-20.04
    steps:
      - uses: actions-ecosystem/action-remove-labels@556e306
        with:
          github_token: ${{ secrets.github_token }}
          labels: pr-test-queue

  build:
    name: Build
    runs-on: ubuntu-20.04
    env:
      PINNED_TOOLS: true
      TOOLS_DIR: ${{ github.workspace }}/tools
    defaults:
      run:
        working-directory: kubecf

    steps:
      # Checkout kubecf
      - name: Checkout KubeCF
        uses: actions/checkout@v2
        with:
          path: kubecf
          fetch-depth: 0
          submodules: recursive

      # Python setup
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Caching tools like helm, jq, git, y2j, yamllint etc
      - name: cache.tools
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/tools
          key: ${{ runner.os }}-tools

      # Install tools
      - run: make tools-install

      # Generate kubecf bundle
      - run: make kubecf-bundle
        env:
          TARGET_FILE: ${{ github.workspace }}/kubecf-bundle.tgz

      # Create tgz of kubecf bundle
      - run: |
          mkdir bundle
          tar xf kubecf-bundle.tgz -C bundle
        working-directory: ${{ github.workspace }}

      # Upload generated tgz bundle
      - name: Upload bundle
        uses: actions/upload-artifact@v2
        with:
          name: kubecf-bundle.tgz
          path: ${{ github.workspace }}/bundle

  tests:
    name: Tests
    runs-on: ubuntu-20.04
    continue-on-error: ${{ matrix.experimental }}
    needs: build
    env:
      # For KubeCF
      PINNED_TOOLS: true
      TOOLS_DIR: ${{ github.workspace }}/tools
      FEATURE_AUTOSCALER: "true"
      # For catapult
      # Note that credentials-related parts are in the individual steps
      BACKEND: gke
      DOWNLOAD_CATAPULT_DEPS: "false"
      CLUSTER_NAME: ci-${{ github.run_id }}-${{ matrix.backend }}
    defaults:
      run:
        working-directory: kubecf

    # Matrix to test diego and eirini
    strategy:
      matrix:
        include:
          - backend: diego
            experimental: false
          - backend: eirini
            experimental: false

    steps:
      # Checkout kubecf
      - name: Checkout KubeCF
        uses: actions/checkout@v2
        with:
          path: kubecf
          submodules: recursive
        timeout-minutes: 1

      # We need catapult to create Kubernetes clusters
      - name: Checkout catapult
        uses: actions/checkout@v2
        with:
          repository: SUSE/catapult
          path: catapult
        timeout-minutes: 1

      # Python setup
      - uses: actions/setup-python@v2
        with:
          # Force 3.8 because google-cloud-sdk is incompatible with 3.9
          # https://issuetracker.google.com/issues/170125513
          python-version: '3.8'
        timeout-minutes: 1

      # Caching tools like helm, jq, git, y2j, yamllint etc
      - name: cache.tools
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/tools
          key: ${{ runner.os }}-tools
        timeout-minutes: 5

      # Install tools
      - run: make tools-install
        timeout-minutes: 1 # this should take ~ 20 seconds

      # Add tools to path
      - name: Add tools to path
        run: echo "${{ github.workspace }}/kubecf/output/bin" >> "${GITHUB_PATH}"
        timeout-minutes: 1

      # Download chart bundle
      - id: download-bundle
        name: Download chart bundle
        uses: actions/download-artifact@v2
        with:
          name: kubecf-bundle.tgz
          # The artifact upload/download creates an extra directory
          path: ${{ github.workspace }}/kubecf-bundle
        timeout-minutes: 1

      # Start SSH agent for catapult
      - name: Start SSH agent
        if: env.BACKEND == 'aks'
        run: |
          set -o errexit -o pipefail -o nounset
          eval "$(ssh-agent -s)"
          ssh-keygen -t rsa -b 4096 -N '' -C "KubeCF CI #${{ github.run_id }}" -f ssh-key
          ssh-add ssh-key
          echo "::add-mask::$(cat ssh-key.pub)"
          rm -f ssh-key ssh-key.pub
          echo "SSH_AUTH_SOCK=${SSH_AUTH_SOCK}" >> "${GITHUB_ENV}"
          echo "SSH_AGENT_PID=${SSH_AGENT_PID}" >> "${GITHUB_ENV}"
        timeout-minutes: 1

      # set GKE secret. TBD: use vault instead
      - name: set GKE_CRED_JSON
        if: env.BACKEND == 'gke'
        run: |
          json_file="$(mktemp)"
          echo "$GKE_CRED_JSON" > "${json_file}"
          echo "GKE_CRED_JSON=${json_file}" >> "${GITHUB_ENV}"
        env:
          GKE_CRED_JSON: ${{ secrets.GKE_CRED_JSON }}
        timeout-minutes: 1

      # Cache catapult's common tools
      - name: cache.catapult-common-tools
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/catapult/modules/common/bin
          key: ${{ runner.os }}-catapult-common-tools
        timeout-minutes: 1

      # Deploy k8s cluster
      - run: make k8s
        working-directory: catapult
        env:
          GKE_CLUSTER_NAME: kubecf-ci-${{ github.run_id }}-${{ matrix.backend }}
          OWNER: ${{ github.repository_owner }}
          DEBUG_MODE: true
          GKE_NODE_COUNT: 1
          GKE_PREEMPTIBLE: false
          GKE_INSTANCE_TYPE: n2d-highcpu-16
          EXTRA_LABELS: '{"ci": "${{ github.run_id }}"}'
        timeout-minutes: 20 # This should take ~10 minutes.

      - name: Set Up GKE Configuration Directory
        if: env.BACKEND == 'gke'
        working-directory: catapult/build${{ env.CLUSTER_NAME }}
        run: |
          . .envrc
          echo "CLOUDSDK_CONFIG=${CLOUDSDK_CONFIG}" >> "${GITHUB_ENV}"
        timeout-minutes: 1

      # Providing kubeconfig for debugging
      - name: export KUBECONFIG
        run: |
          set -o errexit -o nounset -o pipefail
          source .envrc
          echo "KUBECONFIG=${KUBECONFIG}" >> "${GITHUB_ENV}"
          # Debugging aid; should be safe as the cluster will be torn down
          # at the end of the run.
          kubectl config view --minify --flatten | gzip | base64 --wrap=0
        working-directory: catapult/build${{ env.CLUSTER_NAME }}
        timeout-minutes: 1

      # TBD: Don't generate values.yaml
      - name: Generate KubeCF Configuration
        run: exec "${GITHUB_WORKSPACE}/kubecf/.github/workflows/pull-request-ci/kubecf-gen-config.sh"
        env:
          AUTOSCALER: "true"
          ENABLE_EIRINI: ${{ matrix.backend == 'eirini' }}
        timeout-minutes: 1

      # Helm install cf-operator
      - run: make cf-operator-apply
        env:
          CF_OPERATOR_URL: ${{ github.workspace }}/kubecf-bundle/cf-operator.tgz
        timeout-minutes: 1 # This should take ~10 seconds.

      # Wait for cf-operator pods to be ready
      - run: make cf-operator-wait
        timeout-minutes: 1 # This should take ~30 seconds.

      # Helm install kubecf
      - name: Install KubeCF
        run: |
          if [[ "${FEATURE_EIRINI}" != "true" ]]; then
            # `make kubecf-apply` gets confused if the values is `false`.
            unset FEATURE_EIRINI
          fi
          make kubecf-apply
        env:
          CHART: ${{ github.workspace }}/kubecf-bundle/kubecf_release.tgz
          FEATURE_EIRINI: ${{ matrix.backend == 'eirini' }}
          VALUES: ${{ github.workspace }}/kubecf-values.yaml
        timeout-minutes: 1 # This should take ~30 seconds.

      # Wait for kubecf pods to be ready
      - run: make kubecf-wait
        timeout-minutes: 30 # This should take ~15 minutes.

      # Run smoke tests
      - run: make smoke-tests
        timeout-minutes: 10

      # Run brain tests
      # - run: make brain-tests

      # Run sits tests
      - run: make sync-integration-tests
        if: matrix.backend == 'diego'
        timeout-minutes: 5

      # Run CATs
      - run: make acceptance-tests
        timeout-minutes: 180

      # Get resource info for debugging
      - name: Get Resource Info
        if: always()
        run: |
          set +o errexit
          gcloud auth activate-service-account --key-file=${GKE_CRED_JSON}
          resources=(
            BOSHDeployment
            QuarksJob
            QuarksStatefulSet
            Job
            StatefulSet
            Endpoints
            pods
          )

          echo "Getting namespaces..."
          kubectl get namespaces --output=wide
          for namespace in cf-operator kubecf ; do
            for resource in "${resources[@]}" ; do
              printf "%bGetting %s:%s...%b\n" "\e[0;1;33m" "${namespace}" "${resource}" "\e[0m"
              kubectl get "${resource}" --namespace="${namespace}" --output=wide
            done
          done
        timeout-minutes: 5

      # Upload kubecf's values.yaml for debugging
      - name: Upload config
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.backend }}-values.yaml
          path: ${{ github.workspace }}/kubecf-values.yaml
        timeout-minutes: 5

      # Fetch logs for debugging
      - name: Fetch logs
        if: always()
        run: |
          gcloud auth activate-service-account --key-file=${GKE_CRED_JSON}
          # Running klog.sh twice will grab logs from both namespaces
          dev/kube/klog.sh -f -r cf-operator
          dev/kube/klog.sh -f -r
        timeout-minutes: 60

      # Upload logs for debugging
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.backend }}-klog.tgz
          path: ${{ github.workspace }}/kubecf/klog.tar.gz
        timeout-minutes: 5

      # Teardown created k8s cluster
      - name: kubernetes:teardown
        if: always()
        run: |
          set +o errexit
          # Remove any terraform locks, because we don't care if the previous run
          # has finished successfully (e.g. on cancel).
          find "build${CLUSTER_NAME}" -name '.terraform.*.lock*' -delete
          make clean
        working-directory: catapult
        env:
          GKE_CLUSTER_NAME: kubecf-ci-${{ github.run_id }}-${{ matrix.backend }}
        timeout-minutes: 20
