name: CI
on:
  # When a PR is approved, add the queue label
  pull_request_review:
    types: [submitted]

if: contains(github.event.pull_request.labels.*.name, 'pr-test-queue') && github.event.pull_request.base.ref == 'master' && contains(github.event.pull_request.reviews.*.state, 'APPROVED')

jobs:
  dequeue:
    name: dequeue
    runs-on: ubuntu-20.04
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.github_token }}
          labels: pr-test-queue
